### ISSUE TITLE
LTO test crashes ld when building with dwarf exceptions

### ISSUE THREAD

**Issue by Andne** [niXman/mingw-builds#379]
I've been running builds from the develop branch, and am failing one of the tests whenever I build for i686 with dwarf exceptions.  The -flto test generate the following error in lto_int.o-link.log:
```
g++ -s -m32 lto_int.o lto_test.o -flto -o lto_test.exe
collect2.exe: error: ld terminated with signal 22 [Aborted]

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
I have built with sjlj exceptions and built x86_64 with seh exceptions and neither build saw any errors.  This is occuring with gcc 4.8.2, gcc 4.8.4, and gcc 4.6.4.  So far I have only built with posix threads, but I am in the process of building with win32 threads to see if there is a difference, but I doubt there will be.  Is this just a known issue with i686 ld?  Maybe it's related to exception handling inside ld during lto since it appears that the toolchain used is one that has the same exception model as the target.

**Comment by niXman** [comment]
From time to time I faced this bug, but I do not know why it was there...

**Comment by Andne** [comment]
I'm confused, you've seen this issue but it doesn't always occur on a given build?  If so, then it seems like there's some with a specific build.  If it's an issue that plagues a given configuration, then shouldn't the compiler not be built with that feature or not tested when those settings are in effect?
