### ISSUE TITLE
Merge develop and master?

### ISSUE THREAD

**Issue by Andne** [niXman/mingw-builds#390]
When I first started trying to use mingw-builds I ran into trouble because I was using the master branch, and was told to use the develop branch.  I've been using it since, but I don't understand why the develop branch is essentially the primary branch instead of master.  Especially since master doesn't work at all currently.  Are there other plans here that I am unaware of, or should develop be merged into master?

It seems to me that if other people try to use this project, it would make a lot more sense to them for master to the be the current mostly-stable branch to work from and other branches are for specific development activities.

**Comment by niXman** [comment]
I was planning to merge develop and master branches when gcc-5 is released. gcc-5 is now released, but I still can not build it because of this bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65926

**Comment by Andne** [comment]
That's an annoying little bug, looks like they may need to add a MinGW build to the their test suite ;)

**Comment by niXman** [comment]
It is unlikely that someone would agree this =)
