### ISSUE TITLE
Support New and deprecated platforms

### ISSUE THREAD

**Issue by ytrezq** [niXman/mingw-builds#404]
Today it is possible to compile dlls using winAPI for ARM and ARM64 *(Hacked version of windows RT can run unsigned native code)*.
Windows and visual studio supported Alpha; PowerPC; Mips and IA64 in the past. While it restricts to outdated Windows® versions, getting those is the best way to run desktop windows apps if you have the source code.

**Comment by niXman** [comment]
> Today it is possible to compile dlls using winAPI for ARM and ARM64

If it is a question, it is better to ask it here: mingw-w64-public@lists.sourceforge.net

**Comment by ytrezq** [comment]
@niXman this is not a question, you didn’t created builds for those platforms.
