### ISSUE TITLE
Specify custom gcc compile options

### ISSUE THREAD

**Issue by jeroenooms** [niXman/mingw-builds#408]
I would like to build a gcc 4.9.2 without SSE optimization, but I have a hard time figuring out where to set the custom `-mno-sse` option. I tried this:

```
./build --mode=gcc-4.9.2 --rt-version=v3 --arch=i686 --exceptions=sjlj --static-gcc --threads=win32 --enable-languages=c,c++,fortran --cflags='-mno-sse'
```

But that gives:

> configure: error: unrecognized option: `-mno-sse'

**Comment by niXman** [comment]
Which `configure` gives this error? GCC?

**Comment by jeroenooms** [comment]
Yes

**Comment by niXman** [comment]
Please add this line: `echo FOO=\"${3}\"` between the lines 681-682 into `library/functions.sh` file and show me the output.

**Comment by jeroenooms** [comment]
```
-> gcc-4.9.2
---> gcc-4.9.2.tar.bz2 downloaded
---> gcc-4.9.2.tar.bz2 unpacked
---> patched
--> configure...FOO="--host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i                                                                                            686-w64-mingw32 --prefix=/mingw32 --with-sysroot=/home/Jeroen/mingw-gcc-4.9.2/i6                                                                                            86-492-win32-sjlj-rt_v4-s/mingw32 --with-gxx-include-dir=/mingw32/i686-w64-mingw                                                                                            32/include/c++ --enable-static --disable-shared --enable-targets=all --enable-mu                                                                                            ltilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable                                                                                            -threads=win32 --enable-libgomp --enable-libatomic --enable-lto --enable-graphit                                                                                            e --enable-checking=release --enable-fully-dynamic-string --enable-version-speci                                                                                            fic-runtime-libs --enable-sjlj-exceptions --disable-isl-version-check --disable-                                                                                            cloog-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-b                                                                                            ootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror                                                                                             --disable-symvers --with-gnu-as --with-gnu-ld --with-arch-32=i686 --with-arch-6                                                                                            4=nocona --with-tune-32=generic --with-tune-64=core2 -mno-sse --with-libiconv --                                                                                            with-system-zlib --with-gmp=/home/Jeroen/mingw-gcc-4.9.2/prerequisites/i686-w64-                                                                                            mingw32-static --with-mpfr=/home/Jeroen/mingw-gcc-4.9.2/prerequisites/i686-w64-m                                                                                            ingw32-static --with-mpc=/home/Jeroen/mingw-gcc-4.9.2/prerequisites/i686-w64-min                                                                                            gw32-static --with-isl=/home/Jeroen/mingw-gcc-4.9.2/prerequisites/i686-w64-mingw                                                                                            32-static --with-cloog=/home/Jeroen/mingw-gcc-4.9.2/prerequisites/i686-w64-mingw                                                                                            32-static --enable-cloog-backend=isl --with-pkgversion="i686-win32-sjlj, Built b                                                                                            y MinGW-W64 project" --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFL                                                                                            AGS="-O2 -pipe -mno-sse -I/home/Jeroen/mingw-gcc-4.9.2/i686-492-win32-sjlj-rt_v4                                                                                            -s/mingw32/opt/include -I/home/Jeroen/mingw-gcc-4.9.2/prerequisites/i686-zlib-st                                                                                            atic/include -I/home/Jeroen/mingw-gcc-4.9.2/prerequisites/i686-w64-mingw32-stati                                                                                            c/include" CXXFLAGS="-O2 -pipe -mno-sse -I/home/Jeroen/mingw-gcc-4.9.2/i686-492-                                                                                            win32-sjlj-rt_v4-s/mingw32/opt/include -I/home/Jeroen/mingw-gcc-4.9.2/prerequisi                                                                                            tes/i686-zlib-static/include -I/home/Jeroen/mingw-gcc-4.9.2/prerequisites/i686-w                                                                                            64-mingw32-static/include" CPPFLAGS="" LDFLAGS="-pipe -L/home/Jeroen/mingw-gcc-4                                                                                            .9.2/i686-492-win32-sjlj-rt_v4-s/mingw32/opt/lib -L/home/Jeroen/mingw-gcc-4.9.2/                                                                                            prerequisites/i686-zlib-static/lib -L/home/Jeroen/mingw-gcc-4.9.2/prerequisites/                                                                                            i686-w64-mingw32-static/lib -Wl,--large-address-aware""
error!
```

**Comment by niXman** [comment]
Hmm, this is strange... CFLAGS and CXXFLAGS looks as expected...

**Comment by jeroenooms** [comment]
But there is a fifth `-mno-sse` in there outside of `CFLAGS`: 

```
... --with-tune-64=core2 -mno-sse --with-libiconv ...
```

Should that one be there as well?

**Comment by niXman** [comment]
Oh yeah, I didn't notice it. I'll try to figure it out...

> Should that one be there as well?
No.

**Comment by niXman** [comment]
This is strange, but I can't reproduce your error.

run cmd: `./build --buildroot=/c/mingw492 --mode=gcc-4.9.2 --rt-version=v3 --arch=i686 --exceptions=sjlj --static-gcc --threads=win32 --enable-languages=c,c++,fortran --cflags='-mno-sse'`

gcc configure cmd: `FOO="--host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32 --prefix=/mingw32 --with-sysroot=/c/mingw492/i686-492-win32-sjlj-rt_v3-s/mingw32 --with-gxx-include-dir=/mingw32/i686-w64-mingw32/include/c++ --enable-static --disable-shared --enable-targets=all --enable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=win32 --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --enable-sjlj-exceptions --disable-isl-version-check --disable-cloog-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch-32=i686 --with-arch-64=nocona --with-tune-32=generic --with-tune-64=core2 --with-libiconv --with-system-zlib --with-gmp=/c/mingw492/prerequisites/i686-w64-mingw32-static --with-mpfr=/c/mingw492/prerequisites/i686-w64-mingw32-static --with-mpc=/c/mingw492/prerequisites/i686-w64-mingw32-static --with-isl=/c/mingw492/prerequisites/i686-w64-mingw32-static --with-cloog=/c/mingw492/prerequisites/i686-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion="i686-win32-sjlj, Built by MinGW-W64 project" --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFLAGS="-O2 -pipe -mno-sse -I/c/mingw492/i686-492-win32-sjlj-rt_v3-s/mingw32/opt/include -I/c/mingw492/prerequisites/i686-zlib-static/include -I/c/mingw492/prerequisites/i686-w64-mingw32-static/include" CXXFLAGS="-O2 -pipe -mno-sse -I/c/mingw492/i686-492-win32-sjlj-rt_v3-s/mingw32/opt/include -I/c/mingw492/prerequisites/i686-zlib-static/include -I/c/mingw492/prerequisites/i686-w64-mingw32-static/include" CPPFLAGS="" LDFLAGS="-pipe -L/c/mingw492/i686-492-win32-sjlj-rt_v3-s/mingw32/opt/lib -L/c/mingw492/prerequisites/i686-zlib-static/lib -L/c/mingw492/prerequisites/i686-w64-mingw32-static/lib -Wl,--large-address-aware""
`

**Comment by jeroenooms** [comment]
Strange, let me wipe everything and try again.

**Comment by jeroenooms** [comment]
Hmm strange, I removed everything started from scratch and now I don't get this error anymore. It now fails later in the process though:

```
In file included from ./kinds.h:75:0,
                 from ../../../../../../src/gcc-4.9.2/libgfortran/libgfortran.h:243,
                 from ../../../../../../src/gcc-4.9.2/libgfortran/fmain.c:4:
../../../../../../src/gcc-4.9.2/libgfortran/kinds-override.h:40:5: error: #error "Where has __float128 gone?"
 #   error "Where has __float128 gone?"
```

See full [make.log](http://www.stat.ucla.edu/~jeroen/mingw-w64/make.log). But this looks like a bug in gcc, not the build script.

**Comment by niXman** [comment]
Yes, this is GCC bug.

Closed.
