### ISSUE TITLE
File tcl86.dll not included in /opt/bin

### ISSUE THREAD

**Issue by jeroenooms** [niXman/mingw-builds#411]
My build finished (yay). My application requires tcl/tk so I was happy to see that this is bundled with mingw-builds. However I noticed that `i686-492-win32-sjlj-rt_v3-s` contains:

```
./mingw32/opt/include/tcl.h
./mingw32/opt/include/tk.h
./mingw32/opt/lib/libtcl86.dll.a
./mingw32/opt/lib/libtk86.dll.a
```

It also contains `/opt/bin/tk86.dll` however it does not have runtime files files `tcl86.dll`, `tclreg13.dll`, `tcldde14.dll`. Is this a bug, or are these files not required for static gcc?

**Comment by niXman** [comment]
Yes, this is a bug. Now fixed in the `develop` branch.

Closed.
