### ISSUE TITLE
Suggestion to enable `-fno-ident` option when building mingw compiler/runtime binaries

### ISSUE THREAD

**Issue by vszakats** [niXman/mingw-builds#412]
When enabled, this option will instruct gcc not to include a public string identified with `.ident` in each generate object file. That strings contain values similar to these, depending on mingw version and flavor:

`GCC: (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project) 4.8.4`
`GCC: (x86_64-win32-sjlj-rev0, Built by MinGW-W64 project) 5.1.0`

These strings from mingw runtime object are accumulated in great numbers in final applications build using mingw and thus increase the size of said binaries both on disk and in memory. Enabling this option would eliminate this overhead.

**Comment by niXman** [comment]
You are able to successfully build GCC(using mingw-builds scripts) using this option?

**Comment by vszakats** [comment]
I haven't tried building GCC itself with this option, but I'm using it successfully while building [1] application objects using mingw. These strings don't appear to be referenced anywhere, so I believe it should create no problems when enabled while building GCC itself.

[1] https://ci.appveyor.com/project/vsz/harbour-core/branch/master

**Comment by niXman** [comment]
I'll try to build MinGW using this option in the next week.

Closed.

**Comment by vszakats** [comment]
Thanks a lot!

**Comment by White-Tiger** [comment]
thanks for building without and @vszakats for hinting me about this option at all :P 
It doesn't seem to be an issue on Linux as strip can remove this .ident/.comment section, but that doesn't seem to work for Windows. Seems to be at the end of the .rdata section...
Also Linux doesn't load these sections into memory, but I doubt that would be the case on Windows

Will safe me 1.8k when the compiler is updated ;)
Lookes like this for MSYS (from one GCC version) :
> GCC: (Rev3, Built by MSYS2 project) 5.2.0
> GCC: (Rev2, Built by MSYS2 project) 5.2.0

**Comment by vszakats** [comment]
@niXman Not sure I can its effect in the latest 5.2.0 mingw build. Were you be able to enable it? or what were the results of your tests?
