### ISSUE TITLE
Setting -fno-asynchronous-unwind-tables changes exception model

### ISSUE THREAD

**Issue by jeroenooms** [niXman/mingw-builds#416]
Not sure if this is a bug, and if so if it is a bug in the buid script or mingw-w64:

I am using `x86_64-493-win32-seh-rt_v3-s`. However when passing `-fno-asynchronous-unwind-tables` to `g++` it switches to `sjlj` exceptions. You can use [this test](http://stackoverflow.com/questions/17967597/obtaining-current-gcc-exception-model) to reproduce the problem:

```c
struct S { ~S(); };
void bar();
void foo() {
  S s;
  bar();
}
```

You can verify that the output contains sjlj symbols 

```
g++ -fno-asynchronous-unwind-tables -S test.c -o test.s
cat test.s
```

**Comment by niXman** [comment]
It would be better if you write to GCC developers: gcc-help@gcc.gnu.org
