### ISSUE TITLE
gdb runtime dependencies

### ISSUE THREAD

**Issue by jeroenooms** [niXman/mingw-builds#417]
I built a `--static-gcc` version of gcc 4.9.3, however for size limitations I am not shipping the `./opt` dir in my bundle to the end user. Everything works except for `gdb.exe` gives an error about missing python.

Is it possible to statically link libpython into GDB to avoid runtime dependencies? Or alternatively, maybe you should copy the required `.dll` files from `./opt` into `./bin` along with `gdb.exe` itself?

![screenshot](http://i.imgur.com/lsGmszT.png)

**Comment by niXman** [comment]
> Is it possible to statically link libpython into GDB to avoid runtime dependencies?

I do not know, I have not tried.

> Or alternatively, maybe you should copy the required .dll files from ./opt into ./bin along with gdb.exe itself?

No, Python is installed in the 'opt/bin' directory in order to avoid conflicts with other Python that is already installed by the user.
