### ISSUE TITLE
gendef binary missing

### ISSUE THREAD

**Issue by carlkl** [niXman/mingw-builds#436]
gendef.exe is missing in the some of the newer binary builds found on SF. It seems to be commented out in the scripts found in the archive https://github.com/niXman/mingw-builds/files/987827/mingw-builds.zip attached to https://github.com/niXman/mingw-builds/issues/431#issuecomment-300278600

**Comment by niXman** [comment]
Done in GCC-7.1-rev1 builds.

Closed.
