### ISSUE TITLE
Compilation of gcc-5.3.0 failed

### ISSUE THREAD

**Issue by holgern** [niXman/mingw-builds#439]
In file included from ../../../../src/gcc-5.3.0/gcc/cp/except.c:1023:0:
cfns.gperf: In function 'const char* libc_name_p(const char*, unsigned int)':
cfns.gperf:101:1: error: 'const char* libc_name_p(const char*, unsigned int)' redeclared inline with 'gnu_inline' attribute
cfns.gperf:26:14: note: 'const char* libc_name_p(const char*, unsigned int)' previously declared here
cfns.gperf: At global scope:
cfns.gperf:26:14: warning: inline function 'const char* libc_name_p(const char*, unsigned int)' used but never defined
make[3]: *** [Makefile:1065: cp/except.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/c/msys2/i686-530-posix-dwarf-rt_v4-rev0/build/gcc-5.3.0/gcc'
make[2]: *** [Makefile:4375: all-stage1-gcc] Error 2
make[2]: Leaving directory '/c/msys2/i686-530-posix-dwarf-rt_v4-rev0/build/gcc-5.3.0'
make[1]: *** [Makefile:19015: stage1-bubble] Error 2
make[1]: Leaving directory '/c/msys2/i686-530-posix-dwarf-rt_v4-rev0/build/gcc-5.3.0'
make: *** [Makefile:907: all] Error 2

I found a fix for this: http://gcc.gnu.org/viewcvs/gcc?view=revision&revision=233720 
as described here https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69959.

How can this be applied?

**Comment by niXman** [comment]
please make the PR into `develop` branch.

**Comment by niXman** [comment]
and yes, you should create the patch for GCC sources tree.

**Comment by niXman** [comment]
or you can build `gcc-5-branch` instead.

**Comment by holgern** [comment]
Thank you for your fast response. I will take a look into the different solutions.
