### ISSUE TITLE
CDPATH env var may interfere w/ build script

### ISSUE THREAD

**Issue by vburdo** [niXman/mingw-builds#440]
Hi.

I tried this build script and immediately ran into problem.
The source of the problem was **CDPATH** env var which pointed to the tree with "lib" subdirectory.

Error was like `this:`
```
builddir="`pwd`"; cd libcharset && /bin/make all && /bin/make install-lib libdir="$builddir/lib" includedir="$builddir/lib"
make[1]: Entering directory '/d/tools/mingw-gcc-7.1.0/prerequisites-build/x86_64-libiconv-static/libcharset'
if [ ! -d include ] ; then mkdir include ; fi
cp ../../../src/libiconv-1.14/libcharset/include/libcharset.h.in include/libcharset.h
cd lib && /bin/make all
/d/prj/libs/lib
make[2]: Entering directory '/d/prj/libs/lib'
make[2]: *** No rule to make target 'all'.  Stop.
make[2]: Leaving directory '/d/prj/libs/lib'
make[1]: *** [Makefile:34: all] Error 2
make[1]: Leaving directory '/d/tools/mingw-gcc-7.1.0/prerequisites-build/x86_64-libiconv-static/libcharset'
make: *** [Makefile:42: lib/localcharset.h] Error 2
```
The problem was that **CDPATH** was set like this: `CDPATH=/d/prj:/d/prj/libs:/d/prj/3rdparty`
Proposed solution: Unset **CDPATH** at the beginning of "build" by issuing command `unset CDPATH`

**Comment by niXman** [comment]
I'll do it.

Thanks.

**Comment by vburdo** [comment]
One more problem of this kind.
This time **PYTHONHOME** - it interfers w/ python installation

**Comment by niXman** [comment]
I do not understand what you mean..

**Comment by vburdo** [comment]
Having **PYTHONHOME** env var set causes python package build to fail at installation phase.
Solution to this problem is the same: issue `unset PYTHONHOME` at the beginning of "build" script

**Comment by niXman** [comment]
Ok, thanks. I'll do it.
