### ISSUE TITLE
Enable colorized diagnostic messages for CMD ?

### ISSUE THREAD

**Issue by lhmouse** [niXman/mingw-builds#441]
### Introduction

This is a handwritten [ANSI escape code](https://en.wikipedia.org/wiki/ANSI_escape_code) parser. It implements only a handful of commands, but shall suffice for GCC.

Colored diagnostic messages are supported **natively** on Windows 7 - that is, not only in MinTTY or BASH whatsoever, but also in CMD.

There shouldn't be any problems in the case of Windows XP, but I have not tested it.

### Patch

For `gcc-7-branch`: [0018-gcc-7-branch-diagnostic-color.c.patch.txt](https://github.com/niXman/mingw-builds/files/1281934/0018-gcc-7-branch-diagnostic-color.c.patch.txt)

### Screenshot

![gcc-7-colorized-diagnostic-messages](https://user-images.githubusercontent.com/5071344/30124214-07593892-9367-11e7-843f-802aa6cad587.png)

**Comment by niXman** [comment]
Great, thank you!

**Comment by lhmouse** [comment]
There is an [updated version](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gcc-git/0018-gcc-7-branch-Enable-a-native-GCC-to-color-diagnostic-messages-sen.patch). A few typos in comments have been fixed. There is also a new handler for the `ESC [ n J` sequence, which completes the feature list, although GCC does not make use of it at the moment.

**Comment by niXman** [comment]
thanks.

closed.
