### ISSUE TITLE
not able to build gnat in 32 bit multilib versions greater than 4.9

### ISSUE THREAD

**Issue by revelator** [niXman/mingw-builds#443]
Not sure where this bug stems from, but gnat chokes on the 128 bit sse mechanics when compiling a 32 bit multilib version. I guess that is the reason why none of the builds have it anymore since 4.9.2-rev2 ?.

**Comment by niXman** [comment]
Hi,

I have no free time to support gnat also.
Will be great if anyone(may be you) do it..
