### ISSUE TITLE
gcc 4.9.4

### ISSUE THREAD

**Issue by byteblob** [niXman/mingw-builds#444]
Hi,
I'm trying to build mingw32 with gcc 4.9.4. I'm using msys2 **32bit** and mingw-builds' develop branch, which seem to run fine. I'm using this command line:
```build --mode=gcc-4.9.4 --enable-languages=c,c++ --arch=i686 --exceptions=dwarf --threads=win32 --use-lto --no-multilib```
The readme here lists gcc 4.9.4 as one of the tested builds, but when I've tried, the build script downloads the gcc sources from:
```sf.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/```
where there is no source for the 4.9.4 *!!*
Apparently the build script defaults to dowload the latest gcc version, which at the moment is 7.something, but that's not the correct version :p
Any inputs?

**Comment by niXman** [comment]
> The readme here lists gcc 4.9.4 as one of the tested builds, but when I've tried, the build script downloads the gcc sources from:
sf.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/

Why do you think so?
The link to the gcc-4.9.4 sources is specified in the gcc-4.9.4 recipe:
https://github.com/niXman/mingw-builds/blob/develop/scripts/gcc-4.9.4.sh#L43

> Apparently the build script defaults to dowload the latest gcc version, which at the moment is 7.something, but that's not the correct version.

Because this version is specified as default host toolchain version:
https://github.com/niXman/mingw-builds/blob/develop/library/config-win.sh#L41

Also I recommend to delete `--use-lto` option, because it almost never works...

`./build --mode=gcc-4.9.4 --enable-languages=c,c++ --arch=i686 --exceptions=dwarf --threads=win32 --no-multilib --buildroot=/c/mingw494 --bootstrap --rt-version=v5 --jobs=2`

**Comment by byteblob** [comment]
It's the first time I'm using msys, so I had some confusion about the compiler provided with msys (which is not there, but I thought there was one), the toolchain used to build mingw, and the source used for mingw itself.

I'm trying again the build, and you may want to know that with the --jobs=4 option the build gives an error. Unfortunately I didn't keep the make.log :p
![4jobs](https://user-images.githubusercontent.com/9271440/32703600-941716c6-c7f8-11e7-9465-e976a45a4dc4.png)
With only 1 job, it seems to work (crossing fingers):
![1job](https://user-images.githubusercontent.com/9271440/32703623-c7f4f99a-c7f8-11e7-95d1-c52ddf3dd490.png)

I guess you can close the "gcc 4.9.4" issue. Thanks :)

**Comment by byteblob** [comment]
I want to add a final note for anyone who is building this old gcc version like me.
The build took 6 hours :p

I had to fix 2 files to have it build correctly.
First, in `\mingw-builds\scripts\mingw-w64-crt.sh` I emptied the patches list with `PKG_PATCHES=()`, because it gave the *Not found level* error for `bug-647.patch`.
I noticed that `strtold.c` was already patched, so skipping the patch didn't change anything.
For second, in `\src\gdb-8.0.1\gdb\common\common-utils.h` I had to change the `#define REPLACE_TO_STRING 0` to `1`.

While I haven't tested or run anything, the final tests of the build returned all ok.
Note that I've built a 32bit target with 32bit binaries on a 32bit OS (win7), so, at least for this build, the requirement of *Windows-64bit* stated in the readme, is not necessary.

**Comment by niXman** [comment]
> First, in \mingw-builds\scripts\mingw-w64-crt.sh I emptied the patches list with PKG_PATCHES=(), because it gave the Not found level error for bug-647.patch.
> I noticed that strtold.c was already patched, so skipping the patch didn't change anything.

True, because that bug already fixed in MingW-W64.

> For second, in \src\gdb-8.0.1\gdb\common\common-utils.h I had to change the #define REPLACE_TO_STRING 0 to 1.

Why?

> Note that I've built a 32bit target with 32bit binaries on a 32bit OS (win7), so, at least for this build, the requirement of Windows-64bit stated in the readme, is not necessary.

=)

**Comment by byteblob** [comment]
> Why?

Because the compiler gave an error of `std::to_string not defined`

**Comment by niXman** [comment]
https://sourceforge.net/p/mingw-w64/mailman/message/36115808/

**Comment by byteblob** [comment]
Did you have to change the `#define` like I did?

**Comment by niXman** [comment]
Yes.

**Comment by byteblob** [comment]
Well, thanks for the help and for the build :)
