### ISSUE TITLE
#include_next not working in g++-8

### ISSUE THREAD

**Issue by jeroen** [niXman/mingw-builds#452]
As a temporary workaround for https://github.com/niXman/mingw-builds/issues/450 I was able to build a `--static-gcc` toolchain using `--no-extras`. The basic C stuff works well I was able to build my application.

However for C++ I keep getting errors about `#include_next` in headers:

```
In file included from libjson/Source/JSONMemory.h:4,
                 from libjson/Source/JSONChildren.h:6,
                 from JSONChildren.cpp:1:
C:/gcc8/mingw32/i686-w64-mingw32/include/c++/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
```

and

```
In file included from ../inst/include/Rcpp/platform/compiler.h:100,
                 from ../inst/include/Rcpp/r/headers.h:48,
                 from ../inst/include/RcppCommon.h:38,
                 from ../inst/include/Rcpp.h:27,
                 from Date.cpp:31:
C:/gcc8/mingw32/i686-w64-mingw32/include/c++/cmath:45:15: fatal error: math.h: No such file or directory
 #include_next <math.h>
               ^~~~~~~~
```

I confirmed that `stdlib.h` and `math.h` are definitly installed. Is this perhaps a problem in mingw-w64 or an upstream gcc regression? @mingwandroid

**Comment by jeroen** [comment]
Yes that fixed it! Thank you!

Do you think I should report this problem upstream somewhere?

**Comment by jeroen** [comment]
GCC 8 has been released. Maybe we should comment that out by default?

**Comment by niXman** [comment]
Please explain, what is the relationship between this bug and the release of gcc-8.1?

**Comment by jeroen** [comment]
As I understand it, the bug still persists in gcc 8.1 release.

**Comment by niXman** [comment]
Be better to rewrite the FS patch for gcc-8. I'll do it...
