### ISSUE TITLE
Support for gcc-8.2 and gcc-9.1

### ISSUE THREAD

**Issue by eldiener** [niXman/mingw-builds#477]
Does your scripts support building gcc-8.2 and gcc-9.1 ? Neither is currently listed as gcc versions that can be built using your scripts, but these are the two versions of mingw-w64/gcc I do not have so I would like to build them using your scripts.

**Comment by niXman** [comment]
yes `gcc-8.2` and `gcc-9.1` are supported.

to get the list of supported versions you should look at the file `build` in the `develop` branch: https://github.com/niXman/mingw-builds/blob/develop/build#L111

just nobody updates `README.md` file: https://github.com/niXman/mingw-builds/blob/develop/README.md
