### ISSUE TITLE
Parameters used in official builds previously installed with mingw-w64-install program 

### ISSUE THREAD

**Issue by eldiener** [niXman/mingw-builds#478]
Leaving aside the --mode, --arch, --exception, --threads, and --enable-languages choices, what are the other parameter choices which were used when you built the versions you distributed through the mingw-w64-install program ?

I want to build my final version of mingw-w64/gcc-8.2 and mingw-w64/gcc-9.1 with the same other choices that were used by you in the builds distributed through the mingw-w64-install program.

**Comment by niXman** [comment]
each archive is downloaded by the mingw-w64 installer contains the `build-info.txt` file
