### ISSUE TITLE
Clarification of steps to build

### ISSUE THREAD

**Issue by eldiener** [niXman/mingw-builds#479]
In  the instructions for items number 4 and 5 you write:

4. In the MSYS2 file structure delete the /MinGW directory.
5. Delete the paths pointing to any preinstalled MinGW from the PATH environment variable.

What is the purpose of these instructions ? In MSYS2 I see a /mingw64 where /mingw64/bin is in the PATH. Is this the directory you are referring to in 4. and 5. ? Is not this needed to build a new compiler version of mingw-w64/gcc ?

**Comment by niXman** [comment]
this is necessary because the scripts themselves download and use the necessary version of mingw-w64 toochains: https://github.com/niXman/mingw-builds/blob/develop/library/config-win.sh#L41

**Comment by eldiener** [comment]
So when you say /MingW you also mean /mingw64 ?

**Comment by niXman** [comment]
yes

**Comment by eldiener** [comment]
Thanks !
