### ISSUE TITLE
Can't get ./build to run

### ISSUE THREAD

**Issue by eldiener** [niXman/mingw-builds#480]
When I try to run, from the mingw-builds which has the repository:

`./build --mode=gcc-8.2.0 --buildroot=/home/eldnew8/build/i686-8.2.0 --rev=0 --rt-version=v6 --threads=posix --exceptions=dwarf --arch=i686 --enable-languages=c,c++`

I get the response:

```
-> Checking OS bitness... 64-bit
-> Checking OS type... MINGW32_NT-10.0-17763

remove from PATH any existing MinGW directory. terminate.
```

My PATH is:

`/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`

Any idea what ./build is complaining about ?

**Comment by Furniel** [comment]
You must remove or rename mingw32 and mingw64 folders from your msys2 folder

**Comment by niXman** [comment]
@eldiener look at this: https://github.com/niXman/mingw-builds/blob/develop/library/config-win.sh#L75
