### ISSUE TITLE
Build options question

### ISSUE THREAD

**Issue by eldiener** [niXman/mingw-builds#483]
The official MingW-W64-builds are built with, among others, a '--bootstrap' and a '--bin-compress' option. But even looking at the explanation given when typing './build --help' I can not figure out what these options do. Would you please explain what these mean when building a release ? I have been building my own releases of gcc-8.2, 8.3, and 9.1 without these options and everything is building fine, but I am just curious why I might want to use them.

**Comment by Furniel** [comment]
bootstrapping is the technique for producing a self-compiling compiler. Example:
Without bootstrap gcc 7.2 compiles gcc 9.1
With bootstrap gcc 7.2 compiles tmp version of gcc 9.1, and after that tmp gcc 9.1 compiles final version of gcc 9.1.
As result we have gcc version that was built with all code optimizations and bug fixes added in latest gcc. Theoretically bootstrapped builds should be also more stable.
I also added --bootstrapall flag that allows to build target gcc and all included in gcc libraries with target gcc version

--bin-compress option allows to create mingw-w64 gcc zip archive(same as on sourceforge.net)

**Comment by eldiener** [comment]
Thanks !
