### ISSUE TITLE
Updated revision

### ISSUE THREAD

**Issue by eldiener** [niXman/mingw-builds#485]
When you had previously created new revisions for a particular gcc version of the mingw builds, how did you determine that a new revision was necessary ? Did this somehow follow something in the build history of official gcc versions ? Or was this because of some change(s) to this repository in regard to a particular gcc version ?

**Comment by niXman** [comment]
I have been building the new revisions only because of fixes of something related to MinGW-W64 and/or Windows OS

**Comment by eldiener** [comment]
But how did you know to create a new revision of a particular compiler toolset ? If I look at the compilers that you offered as part of the mingw-w64-install.exe distributions I can see, for instance, for gcc-7.2.0 build revisions 0 and 1. What caused a new build revision in that case, and how did you know to generate the new revision ?

**Comment by niXman** [comment]
I followed the mingw-w64 mailing list and also saw what patches were sent to me in the mingw-builds project - if I saw some important fix - I building the new revision.

**Comment by eldiener** [comment]
OK, thanks !
