### ISSUE TITLE
gcc-9.2.0: libffi/fix_return_size.patch, error=1

### ISSUE THREAD

**Issue by 2underscores-vic** [niXman/mingw-builds#489]
```sh
./build --mode=gcc-9.2.0 --enable-languages=c,c++ --arch=x86_64 \
    --rt-version=v6.0.0 --exceptions=seh --threads=posix
```

```
...
-> libffi
---> libffi-3.2.1.tar.gz downloaded
--> unpack libffi-3.2.1.tar.gz... done
--> patching...
Not found level for patch libffi/fix_return_size.patch, error=1
```

**Comment by niXman** [comment]
@Furniel did you manage to build gcc-9.2?

**Comment by 2underscores-vic** [comment]
You mean gcc compiler per se? Yes

```
-> gcc-9.2.0
---> gcc-9.2.0.tar.xz downloaded
---> gcc-9.2.0.tar.xz unpacked
---> patched
---> configured
---> built
---> installed
```

But then `build` script fails

**Comment by Furniel** [comment]
> 
> 
> @Furniel did you manage to build gcc-9.2?

Yes, https://github.com/Furniel/mingw-builds/releases/tag/gcc-9.2.0

**Comment by Eric-Vignola** [comment]
@Furniel 

can you share the exact command you used to build x86_64-9.2.0-release-win32-seh-rt_v6

**Comment by Furniel** [comment]
@Eric-Vignola 
./build --mode=gcc-9.2.0 --buildroot=/c/mingw920 --threads=win32 --exceptions=seh --arch=x86_64 --rt-version=v6 --jobs=8 --bin-compress
Bootstrapped builds will be later(they need too many time to build)

**Comment by Eric-Vignola** [comment]
@Furniel thanks i'll give it a try later with --bootstrap (or should i do --bootstrapall?, can't tell the difference anymore)

My goal, ultimately, is to build a static toolchain that links against Visual Studio 2015 [using steps outlined here](https://www.spiria.com/en/blog/desktop-software/building-mingw-w64-toolchain-links-specific-visual-studio-runtime-library) with a few tweaks (article instructions is for 2012)

**Comment by Eric-Vignola** [comment]
@Furniel When running your command i see the toolchain that gets pulled is
*7.2.0*. Is this normal?

$ ./build --mode=gcc-9.2.0 --threads=win32 --exceptions=seh --arch=x86_64
--rt-version=v6 --jobs=8 --bin-compress --enable-languages=c,c++,fortran
-> Checking OS bitness... 64-bit
-> Checking OS type... MINGW32_NT-10.0-17134
-> Checking for installed packages... done
-> x86_64 toolchain
*--> x86_64 toolchain is not installed --> download
x86_64-7.2.0-release-posix-seh-rt_v5-rev1.7z... done*

**Comment by Furniel** [comment]
@Eric-Vignola
Yes, gcc 7.2 is used as base gcc for compilation of target gcc

**Comment by 2underscores-vic** [comment]
What about my issue? What is 'level for patch'?

**Comment by Furniel** [comment]
@2underscores-vic 
Can reproduce, but can you check this patch version? Extract and replace patch in mingw-builds\patches\libffi\
[fix_return_size.zip](https://github.com/niXman/mingw-builds/files/3508460/fix_return_size.zip)

If that won't help you can apply patch manually and comment out "libffi/fix_return_size.patch" in mingw-builds\scripts\libffi.sh

**Comment by 2underscores-vic** [comment]
libffi-3.2.1.tar.gz-unpack.log:
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
The file was in tar format w/o gzip... (but still named libffi-3.2.1.tar.gz)

I removed the file and now
```
-> libffi
---> libffi-3.2.1.tar.gz downloaded
--> unpack libffi-3.2.1.tar.gz... done
--> patching... done
--> configure...
 done
--> building... done
--> installing... done
```

Thank you for feedback!
