### ISSUE TITLE
Building 32-bit code with 64-bit compiler

### ISSUE THREAD

**Issue by eldiener** [niXman/mingw-builds#491]
My 64-bit versions of mingw-w64/gcc are all built ( or installed ) with threads=posix and exceptions=seh. Yet if I try to create 32-bit code with such a 64-bit version it always fails at the link step, not finding the necessary 32-bit libraries. I suspect this is because the 64-bit compiler version does not have multilib support. Yet when I look at the options for building it tells me that the default for the 64-bit seh exception model is no-multilib. Is my problem the lack of multilib support and, if so, how do I turn it on so that I can create 32-bit code with the 64-bit compiler ? My current solution is to create 64-bit code with the 64-bit compiler and create 32-bit code with the 32-bit compiler. While this works flawlessly  it would be nicer if I need only build/install a 64-bit compiler on my system for each mingw-w64 release I use and test.

**Comment by niXman** [comment]
> I suspect this is because the 64-bit compiler version does not have multilib support

right, because there is no SEH implementation for 32-bit.

you can build the 64-bit multilib compiler when exceptions=sjlj

**Comment by niXman** [comment]
and yes - SJLJ exceptions are very slow, but if you program using C - it doesn't matter.

**Comment by eldiener** [comment]
I am programming C++. Does the sjlj exception model slowdown affect the speed of processing when an exception is not occuring ?

**Comment by eldiener** [comment]
Never mind I found the info I wanted.
