### ISSUE TITLE
gcc-9.2.0 test failures

### ISSUE THREAD

**Issue by Prince213** [niXman/mingw-builds#492]
I'm building toolchains with this command: `$ ./buildall gcc-9.2.0 --no-multilib --no-extras --jobs=6 --rt-version=trunk --with-default-msvcrt=ucrt --threads=posix --enable-languages=c,c++`
The build process was fine but all toolchains weren't able to pass the test `time_test`.
The error was: `Assertion failed: rc == -1 && (errno == EINVAL) , file E:/mingw-builds/tests/time_test.c, line 146`
Log:
```
-> tests
--> Doesn't need to download
--> Unpack doesn't need
--> gcc      x86_64: "omp_test.c" ...             -> 0 -> done
--> execute x86_64: "omp_test.exe" ...            -> 0 -> done
--> gcc      x86_64: "time_test.c" ...            -> 0 -> done
--> execute x86_64: "time_test.exe" ...
-> 1 -> error. terminate.
```
Any idea?

**Comment by niXman** [comment]
Hi, 
I think the cause of the problem is `--rt-version=trunk --with-default-msvcrt=ucrt`
try to use `--rt-version=v6` instead
if I'm right - you should email to the MinGW-W64 CRT developers: https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/

**Comment by Prince213** [comment]
I have already tried `--rt-version=v6 --with-default-msvcrt=ucrt` and `--rt-version=v6.0.0 --with-default-msvcrt=ucrt` before, but got the same issue.

**Comment by niXman** [comment]
try without `--with-default-msvcrt=ucrt`

**Comment by Prince213** [comment]
Well, that problem disappeared, but got another problem: 32bit binaries couldn't pass the test `filesystem`. 
Log(`filesystem.cpp-compilation.log`):
```
g++ -m32 -O2 -s /e/mingw-builds/tests/filesystem.cpp -std=c++11 -lstdc++fs -o /e/mingw920/i686-920-win32-sjlj-rt_v6/build/tests/i686/filesystem.exe
E:/mingw920/i686-920-win32-sjlj-rt_v6/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: E:/mingw920/i686-920-win32-sjlj-rt_v6/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/libstdc++fs.a(ops.o):(.text$_ZNSt12experimental10filesystem2v115last_write_timeERKNS1_7__cxx114pathENSt6chrono10time_pointINS6_3_V212system_clockENS6_8durationIxSt5ratioILx1ELx1000000000EEEEEERSt10error_code+0xb6): undefined reference to `_imp___wutime32'
collect2.exe: error: ld returned 1 exit status
```

**Comment by Prince213** [comment]
Update: It seems that the problem has been recorded at https://github.com/msys2/MINGW-packages/issues/5183 and was solved by https://github.com/mirror/mingw-w64/commit/0dfb3d3fac964de1080884863c0544f35ed424a5. but that commit is not on the `v6.x` branch. So building the toolchains with `--rt-version=trunk` will solve the problem? I'll build the toolchains soon to verify that.

**Comment by niXman** [comment]
> So building the toolchains with --rt-version=trunk will solve the problem?

I don't know...

> I'll build the toolchains soon to verify that.

Let me know please.

**Comment by Prince213** [comment]
Problem disappeared. Thanks!
