### ISSUE TITLE
Compiling gcc 9.2.0 with mingw-w64 v. 7.0.0 requires setting -D_FORTIFY_SOURCE=0

### ISSUE THREAD

**Issue by MNRK01** [niXman/mingw-builds#496]
This is already a well known issue but I cannot compile gcc 9.2.0 using the mingw-builds scripts and mingw-w64 rt=7.0.0 without setting the following flags:

```
--cflags='-D_FORTIFY_SOURCE=0' --cxxflags='-D_FORTIFY_SOURCE=0'  --ldflags='-fstack-protector'
```

The build fails at the compiling gdb stage with undefined references to __memcpy_chk and related functions.

Therefore a typical calling sequence that leads to successful compilation is:

```
./build --mode=gcc-9.2.0 --arch=i686 --threads=posix --exceptions=sjlj --enable-languages=c,c++,fortran --rt-version=v7.0.0 --jobs=4 --rev=0 --cflags='-D_FORTIFY_SOURCE=0' --cxxflags='-D_FORTIFY_SOURCE=0'  --ldflags='-fstack-protector'
```

I took my hints from [https://github.com/msys2/MINGW-packages/issues/5803](https://github.com/msys2/MINGW-packages/issues/5803).

I am mostly raising this issue to help anyone else struggling with compiling gcc with mingw-w64 rt v. 7.0.0 using your mingw-builds scripts.

I would appreciate keeping this issue open until there is a fix that does not need the extra flags.

Thanks for the excellent work with these scripts.

**Comment by niXman** [comment]
thank you!

will fix it.
