### ISSUE TITLE
undefined resources cause gdb build failure

### ISSUE THREAD

**Issue by Eric-Vignola** [niXman/mingw-builds#497]
On Win10 with msys2 64bit running this command:

./build --mode=gcc-9.2.0 --jobs=10 --arch=x86_64 --bootstrap

I've attached the complete build log, if you scroll to the very end you'll see ld.exe complains about undefined references to "__memcpy_chk", __strcpy_chk", "__memset_chk" and "__strcat_chk" in several .c files.

[make.log](https://github.com/niXman/mingw-builds/files/4057306/make.log)

**Comment by niXman** [comment]
look at this: https://github.com/niXman/mingw-builds/issues/496
