### ISSUE TITLE
Building GCC 9.3 meet some error

### ISSUE THREAD

**Issue by Efreets** [niXman/mingw-builds#503]
Hi,
  Do you have some time to help me to solve the problem with building gcc 9.3 on windows?
  Thanks.

  Here was my information during Build gcc, how it makes, I'm my best to solve the error, but it's no work

  My configure is

../gcc-9.3.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/P/Efreets/gcc930/ --with-sysroot=/P/Efreets/gcc930/ --enable-languages=c,lto,c++,fortran --enable-lto --enable-static --disable-symvers --disable-shared --enable-threads=posix --enable-sjlj-exceptions --with-system-zlib --with-gmp=/P/Efreets/gmp620 --with-mpfr=/P/Efreets/mpfr402 --with-mpc=/P/Efreets/mpc110 --with-isl=/P/Efreets/isl221 --with-zstd=/P/Efreets/zstd144

  It's meet this error

[ -f stage_final ] || echo stage3 > stage_final
make[1]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
make[2]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
make[3]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
rm -f stage_current
make[3]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make[2]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make[2]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
/usr/bin/sh: -c:行6: unexpected EOF while looking for matching `''
/usr/bin/sh: -c:行7: syntax error: unexpected end of file
make[2]: *** [Makefile:11206: all-stage1-libiberty] Error 1
make[2]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make[1]: *** [Makefile:21113: stage1-bubble] Error 2
make[1]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make: *** [Makefile:1003: all] Error 2

  And this is the error line in MakeFile

![eff889e3d134e9e2d88fbbae7fb15c79](https://user-images.githubusercontent.com/11472828/78423480-24eff180-7699-11ea-878c-2ee03c78e78b.png)

![76f4fa84a85768a6c2482d160c8b1d07](https://user-images.githubusercontent.com/11472828/78423485-2b7e6900-7699-11ea-94cd-2019500eec39.png)

I think error line in right, but I can't solve the problem, could you help me ?

  I can't thank you so much, I need you help, Waiting message.

yours sincerely

**Comment by niXman** [comment]
do you use mingw-builds scripts for building GCC?

**Comment by Efreets** [comment]
Thanks for your new mingw-builds Release 5.0,
I will try with it to build gcc 9.3,
but i found Your gcc script was not use the new just-real-time compress tool, which facebook
used ZSTD for Compiler compress code, and the make alway not change which the newer is
make 4.3.

**Comment by niXman** [comment]
you're right, but patches are welcome.

**Comment by Efreets** [comment]
Thanks for you build script, it's help a lot.
Well, could you mind to update some tools to newer, like clang and make, it's too old.
And can you build an official mingw-w64 gcc compiler and upload to sourceforge.net,
it's will help a lots of people all over the world.
Thanks you for the efforts with your opensource work.
On my honor, respect your harding-working

**Comment by niXman** [comment]
> could you mind to update some tools to newer, like clang and make

which branch do you use?

> And can you build an official mingw-w64 gcc compiler and upload to sourceforge.net

yes, I plan to continue to produce the official builds, but I will upload them to this project as releases, because the authors of the mingw-w64 project deprived me of access to the mingw-w64 project and for several months they never answered my letter....
