### ISSUE TITLE
Problem building 8.4.0 with revision v7

### ISSUE THREAD

**Issue by eldiener** [niXman/mingw-builds#506]
When attempting to build, with your script, gcc-8.4.0 with the command line:

./build --arch=i686 --mode=gcc-8.4.0 --rev=0 --buildroot=$HOME/build/i686-8.4.0 --jobs=4 --rt-version=v7 --threads=posix --exceptions=dwarfseh --enable-languages=c,c++

or

./build --arch=x86_64 --mode=gcc-8.4.0 --rev=0 --buildroot=$HOME/build/x86_64-8.4.0 --jobs=4 --rt-version=v7 --threads=posix --exceptions=dwarfseh --enable-languages=c,c++

I receive the error:

-> gcc-8.4.0
--> download gcc-8.4.0.tar.xz... done
--> unpack gcc-8.4.0.tar.xz... done
--> patching...
Not found level for patch gcc/gcc-8-branch-Backport-patches-for-std-filesystem-from-master.patch, error=1

I did pull the latest from the 'develop' branch as of yesterday.

**Comment by niXman** [comment]
https://github.com/niXman/mingw-builds/pull/499

@Furniel did you manage to build gcc-8.4.0 successfully?

**Comment by eldiener** [comment]
No, I have not been able to build gcc-8.4.0 successfully. I see you have a PR for that and I will wait until that is merged to 'develop' and try again.

**Comment by niXman** [comment]
@eldiener done

**Comment by eldiener** [comment]
The PR allowed me to build 8.4.0 without problems.

**Comment by niXman** [comment]
@Furniel thank you!
