### ISSUE TITLE
ignored the lndir command

### ISSUE THREAD

**Issue by ashe27** [niXman/mingw-builds#511]
`--> download zlib-1.2.11.tar.xz... done
--> unpack zlib-1.2.11.tar.xz... done
--> patching... done
/home/JY/mingw-builds/library/functions.sh: line 676: lndir: command not found
--> configure...
error!`

the lndir command was ignored when checking the installation package

**Comment by niXman** [comment]
https://github.com/niXman/mingw-builds/blob/master/library/config-win.sh#L81

**Comment by kov-serg** [comment]
И почему в этом списке нет lndir ?

**Comment by niXman** [comment]
because the one who implemented this feature (this was not originally, regular copying previously used) forgot to add `lndir`.

**Comment by kov-serg** [comment]
What is preventing to fix it?

**Comment by niXman** [comment]
because nobody did pull request =)

**Comment by niXman** [comment]
done: https://github.com/niXman/mingw-builds/commit/1ced8e4788c99ce4bcce2e03dd47a8876a5f4e0f
