### ISSUE TITLE
Undefined reference to `sys_siglist' when building binutils

### ISSUE THREAD

**Issue by longnguyen2004** [niXman/mingw-builds#514]
I'm not sure what caused this, does anyone know?

**Comment by kov-serg** [comment]
LTO cause https://gcc.gnu.org/legacy-ml/gcc/2015-05/msg00084.html

**Comment by longnguyen2004** [comment]
Maybe we should remove LTO from the script, since there are way too many problems with it (`sys_siglist`, `strndup`,...)
