### ISSUE TITLE
Wrong --prefix for GCC

### ISSUE THREAD

**Issue by Prince213** [niXman/mingw-builds#521]
See:
- https://github.com/niXman/mingw-builds/blob/develop/build#L515
- https://github.com/niXman/mingw-builds/blob/develop/scripts/gcc-10.2.0.sh#L72

Should be `$BASE_BUILD_DIR/mingw$(func_get_arch_bit ${BUILD_ARCHITECTURE})` or `$PREFIX`.

**Comment by niXman** [comment]
can you please show the output for each expression?

**Comment by Prince213** [comment]
```
$BASE_BUILD_DIR/mingw$(func_get_arch_bit ${BUILD_ARCHITECTURE}): /e/mingw1020/x86_64-1020-posix-seh-rt_v700/mingw64
$PREFIX: /e/mingw1020/x86_64-1020-posix-seh-rt_v700/mingw64
```

**Comment by Prince213** [comment]
Since other package installs to `$PREFIX`, I would prefer `$PREFIX`. But that makes it confusing why https://github.com/niXman/mingw-builds/commit/1b4471dc2ebd2b298e9f3ba5f368167f20916599 exists in the first place.

**Comment by niXman** [comment]
oh %)

I have no ideas...

**Comment by niXman** [comment]
@Prince213 any news?

**Comment by Prince213** [comment]
None. Maybe we should just change it back to `$PREFIX`, what do you think?

**Comment by niXman** [comment]
yes, we can try :)
