### ISSUE TITLE
[question] Is checking for existing gcc.exe really necessary?

### ISSUE THREAD

**Issue by theodelrieu** [niXman/mingw-builds#526]
Hi,

I've been trying to package a mingw toolchain as a Conan package.

The thing is, I'm using a `msys2` package, and removing anything from this package (i.e. `/mingw32`, `gcc.exe`) is not possible, as it break boundaries between packages.

So what I've done is removing the checks in `library/config-win.sh` that try to locate `gcc.exe`, `i686-w64-stuff-gcc.exe`, and I've successfully built a toolchain afterwards.

My question is: What are the point of these checks? Can they be removed? It is not currently possible to properly build & package a toolchain with those checks.

**Comment by niXman** [comment]
> What are the point of these checks?

this check is needed because the `configure` used by GCC for some reason prefers to use `gcc.exe` from the `/mingw/bin`/`/mingw32/bin`/`/mingw64/bin` directories, even when a different path is specified in the `PATH` env.

**Comment by theodelrieu** [comment]
>this check is needed because the configure used by GCC for some reason prefers to use gcc.exe

Wouldn't it be preferable to patch the configure script instead of removing folders from `msys2`? I guess the hardest part is finding where to patch...

**Comment by niXman** [comment]
sorry, was on vacation.

> Wouldn't it be preferable to patch the configure script instead of removing folders from msys2? I guess the hardest part is finding where to patch...

yes, it's hard to understand what exactly needs to be patched...
the second difficulty is that the configure script is generated by autogen, and it can be quite different in each release. this can lead to the fact that we have to create a patch for each version!

**Comment by theodelrieu** [comment]
> this can lead to the fact that we have to create a patch for each version!

Yuck indeed... But I'm afraid there is no easy solution to allow efficient packaging :/

**Comment by niXman** [comment]
if you have no other questions, close the ticket please.

**Comment by theodelrieu** [comment]
I don't have any questions left, I'll keep patching the `build` script to not look for `gcc.exe` et. al
