### ISSUE TITLE
Why is --enable-wildcard passed during build?

### ISSUE THREAD

**Issue by torarnv** [niXman/mingw-builds#529]
Upstream mingw64 defaults to not expanding wildcards. Why does this build script enable them?

https://github.com/niXman/mingw-builds/blame/7f9ed8fd7fb221ba81d957602c7adc67b97b1341/scripts/mingw-w64-crt.sh#L76

**Comment by niXman** [comment]
I don't remember why, it was done nine years ago =)

patches are welcome!
and please explain why wildcards should be disabled.

thanks.

**Comment by torarnv** [comment]
Understandable 😊 

Msys2 seems to do the same thing: https://github.com/msys2/MINGW-packages/blame/60c5854c234e18023812c86ac5e6d0b6b8d98a65/mingw-w64-crt/PKGBUILD#L52

Most likely based on inspiration from mingw-builds. 

While llvm-mingw doesn't seem to: https://github.com/mstorsjo/llvm-mingw/blob/master/build-mingw-w64.sh

I'd stay the strongest argument is that mingw64 upstream defaults to not expanding wildcards, nor does MSVC. 

It also results in weird issues like `foo.exe سلامممممم` being treated as a wildcard.

**Comment by niXman** [comment]
@torarnv  and? should we disable it or what?
