### ISSUE TITLE
v4.3.5 is not tagged

### ISSUE THREAD

**Issue by kkoehne** [niXman/mingw-builds#530]
The binary packages for x86_64-8.1.0-release-posix-seh-rt_v6-rev0 claim that they were built with v4.3.5.

From build-info.txt:

{code}
version : MinGW-W64-builds-4.3.5
user    : nixman
date    : 05.12.2018-10:29:36 AM
{code]

Anyhow, there's no v-4.3.5 tag in the repository.

**Comment by niXman** [comment]
looks like someone made a mistake...

**Comment by niXman** [comment]
please close this issue.
