### ISSUE TITLE
i686 8.30 issue

### ISSUE THREAD

**Issue by labba** [niXman/mingw-builds#531]
hi
i have succesfully built the x86_64 arch but when i try to build the i686 build i get an error.

this is the command line i executed:
./build --mode=gcc-8.3.0 --arch=i686 --rt-version=v7 --threads=win32 --enable-languages=c,c++

and you can find here the logs :
[make.log](https://github.com/niXman/mingw-builds/files/5505670/make.log)
[configure.log](https://github.com/niXman/mingw-builds/files/5505671/configure.log)

**Comment by niXman** [comment]
hi,

please `cd` into `/home/gcc/mingw-gcc-8.3.0/i686-830-win32-sjlj-rt_v7/build/gcc-8.3.0/i686-w64-mingw32/64/libgcc` dir and put `config.log` here.

thanks!

**Comment by labba** [comment]
sure here you go:
[config.log](https://github.com/niXman/mingw-builds/files/5506221/config.log)

thanks!

**Comment by niXman** [comment]
look at line 112 ;)

**Comment by labba** [comment]
"Fatal error: no compiled in support for x86_64" ? but i have set the build command for compiling an i686 arch .
the tests are compiling with "-m64" and this is targeting i686 .. the test compilation are wrong. no ?

**Comment by niXman** [comment]
try to rebuild using `--no-multilib` flag.

**Comment by labba** [comment]
still fail with different error please see logs (let me know if you need other logs) thanks!

[make.log](https://github.com/niXman/mingw-builds/files/5506608/make.log)
[configure.log](https://github.com/niXman/mingw-builds/files/5506612/configure.log)

the end of the log shows warning  treated as errors:

```
libtool: compile:  /home/gcc/mingw-gcc-8.3.0/i686-830-win32-sjlj-rt_v7/build/gcc-8.3.0/./gcc/xgcc -B/home/gcc/mingw-gcc-8.3.0/i686-830-win32-sjlj-rt_v7/build/gcc-8.3.0/./gcc/ -L/mingw32/i686-w64-mingw32/lib -L/mingw32/mingw/lib -isystem /mingw32/i686-w64-mingw32/include -isystem /mingw32/mingw/include -B/mingw32/i686-w64-mingw32/bin/ -B/mingw32/i686-w64-mingw32/lib/ -isystem /mingw32/i686-w64-mingw32/include -isystem /mingw32/i686-w64-mingw32/sys-include -DHAVE_CONFIG_H -I. -I../../../../../src/gcc-8.3.0/libgomp -I../../../../../src/gcc-8.3.0/libgomp/config/mingw32 -I../../../../../src/gcc-8.3.0/libgomp/config/posix -I../../../../../src/gcc-8.3.0/libgomp -I../../../../../src/gcc-8.3.0/libgomp/../include -Wall -pthread -Werror -g -O2 -pipe -fno-ident -I/home/gcc/mingw-gcc-8.3.0/i686-830-win32-sjlj-rt_v7/mingw32/opt/include -I/home/gcc/mingw-gcc-8.3.0/prerequisites/i686-zlib-static/include -I/home/gcc/mingw-gcc-8.3.0/prerequisites/i686-w64-mingw32-static/include -MT target.lo -MD -MP -MF .deps/target.Tpo -c ../../../../../src/gcc-8.3.0/libgomp/target.c  -DDLL_EXPORT -DPIC -o .libs/target.o
../../../../../src/gcc-8.3.0/libgomp/target.c: In function 'gomp_map_vars':
../../../../../src/gcc-8.3.0/libgomp/target.c:929:21: error: unknown conversion type character 'l' in format [-Werror=format=]
         gomp_fatal ("present clause: !acc_is_present (%p, "
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../../../../src/gcc-8.3.0/libgomp/target.c:37:
C:/msys64/mingw32/i686-w64-mingw32/include/inttypes.h:36:18: note: format string is defined here
 #define PRIu64 "llu"
                  ^
../../../../../src/gcc-8.3.0/libgomp/target.c:929:21: error: unknown conversion type character 'l' in format [-Werror=format=]
         gomp_fatal ("present clause: !acc_is_present (%p, "
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../../../../src/gcc-8.3.0/libgomp/target.c:37:
C:/msys64/mingw32/i686-w64-mingw32/include/inttypes.h:37:18: note: format string is defined here
 #define PRIx64 "llx"
                  ^
../../../../../src/gcc-8.3.0/libgomp/target.c:929:21: error: too many arguments for format [-Werror=format-extra-args]
         gomp_fatal ("present clause: !acc_is_present (%p, "
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
make[4]: *** [Makefile:659: target.lo] Error 1
make[4]: Leaving directory '/home/gcc/mingw-gcc-8.3.0/i686-830-win32-sjlj-rt_v7/build/gcc-8.3.0/i686-w64-mingw32/libgomp'
make[3]: *** [Makefile:904: all-recursive] Error 1
make[3]: Leaving directory '/home/gcc/mingw-gcc-8.3.0/i686-830-win32-sjlj-rt_v7/build/gcc-8.3.0/i686-w64-mingw32/libgomp'
make[2]: *** [Makefile:493: all] Error 2
make[2]: Leaving directory '/home/gcc/mingw-gcc-8.3.0/i686-830-win32-sjlj-rt_v7/build/gcc-8.3.0/i686-w64-mingw32/libgomp'
make[1]: *** [Makefile:14165: all-target-libgomp] Error 2
make[1]: Leaving directory '/home/gcc/mingw-gcc-8.3.0/i686-830-win32-sjlj-rt_v7/build/gcc-8.3.0'
make: *** [Makefile:911: all] Error 2

```

**Comment by niXman** [comment]
did you re-start the build from scratch?
you have to delete everything and restart the build from scratch. (`rm -rf /home/gcc/mingw-gcc-8.3.0`)

**Comment by labba** [comment]
yes i made sure 2 times that indeed i start all over again. 

i have also tried without the "--rt-version=v7" and use the default, but sadly gotten the same results.

**Comment by niXman** [comment]
look at this please:
https://github.com/niXman/mingw-builds/issues/520
https://github.com/niXman/mingw-builds/issues/525

**Comment by labba** [comment]
oh. so it's a known issue.

so i need to manually patch it ? or are you planning to incorporate/integrate it in the existing scripts in the near future ?

**Comment by labba** [comment]
i have added the "0020-libgomp-Don-t-hard-code-MS-printf-attributes.patch" to the PKG_PATCHES that is in the gcc-8.3.0.sh. and putted it inside "mingw-builds\patches\gcc" and compilation now passes.

hope you can add this to your source as well so it would be maintained properly.

thanks!

**Comment by niXman** [comment]
> hope you can add this to your source as well so it would be maintained properly.

patches are welcome! ;)

**Comment by niXman** [comment]
@Prince213 should I close this?

**Comment by Prince213** [comment]
@niXman Yeah. Thanks.
