### ISSUE TITLE
Stucks in building binutils

### ISSUE THREAD

**Issue by guyutongxue** [niXman/mingw-builds#535]
While I was trying to build `binutils`, I get stuck when executing the following command:
```sh
/bin/sh ../../../src/binutils-2.35.1/ld/genscripts.sh "../../../src/binutils-2.35.1/ld" "/build/prerequisites/x86_64-binutils-nomulti/lib" "/build/prerequisites/x86_64-binutils-nomulti" "/build/prerequisites/x86_64-binutils-nomulti" x86_64-w64-mingw32 x86_64-w64-mingw32 x86_64-w64-mingw32 ".deps" "" "i386pep" "/usr/local/lib /lib /usr/lib" yes yes i386pep "x86_64-w64-mingw32"
```
(Originally ld's Makefile from [here](https://github.com/bminor/binutils-gdb/blob/master/ld/Makefile.in#L2290))

I tried debugging this `genscripts.sh` with `-x` flag and found that it was stuck on script `ld/emultempl/pep.em`, line 20. (See [here](https://github.com/bminor/binutils-gdb/blob/master/ld/emultempl/pep.em#L20).)

It seems that the error happened in the function `fragment` (just a simple `cat`, defined [here](https://github.com/bminor/binutils-gdb/blob/master/ld/genscripts.sh#L613)), but I cannot figure out why it happened.

(Sorry for poor English)

**Comment by guyutongxue** [comment]
OK, I got it. When the `cat`'s heredoc is longer than 65535 character, it will be stuck. Seems a bug of MSYS2?

[A minimal script](https://paste.ubuntu.com/p/zBq6htgJJg/) reproduces this issue.

**Comment by Prince213** [comment]
@Guyutongxue You might want to increase your pipe capacity.

**Comment by lurobi** [comment]
I have found this issue as well.  I'm building on Windows with a fresh MSYS2 install and cannot get past the build of binutils.

@Prince213 How do you increase pipe capacity?  I've found solutions to change pipe size for a currently running process, but it isn't clear to me how I would do it for any new process spawned by the shell.

**Comment by lurobi** [comment]
As a work around, I split the heredoc into two with a subshell.  The rest of the binutils build continued without issue.

```patch
@@ -17,7 +17,7 @@

 rm -f e${EMULATION_NAME}.c
 (echo;echo;echo;echo;echo)>e${EMULATION_NAME}.c # there, now line numbers match ;-)
-fragment <<EOF
+(cat <<END1; cat <<END2; ) | fragment
 /* Copyright (C) 2006-2020 Free Software Foundation, Inc.
    Written by Kai Tietz, OneVision Software GmbH&CoKg.

@@ -991,6 +991,7 @@
   return TRUE;
 }

+END1
 static void
 pep_fixup_stdcalls (void)
 {
@@ -2115,7 +2116,7 @@


 static char *
 gld_${EMULATION_NAME}_get_script (int *isfile)
-EOF
+END2
 # Scripts compiled in.
 # sed commands to quote an ld script as a C string.
 sc="-f stringify.sed"

```

Is there a way to patch binutils before the build to accomplish this?

**Comment by Prince213** [comment]
> Is there a way to patch binutils before the build to accomplish this?

First add your patch here: https://github.com/niXman/mingw-builds/tree/develop/patches/binutils.
Then add path to your patch here: https://github.com/niXman/mingw-builds/blob/develop/scripts/binutils.sh#L55.

**Comment by lurobi** [comment]
niXman: Pull request for binutils patch if you want it:

https://github.com/niXman/mingw-builds/pull/536

**Comment by niXman** [comment]
@lurobi merged, thank you!

please close the issue if it solver.

**Comment by guyutongxue** [comment]
Thank you very much!
