### ISSUE TITLE
Gcc 11.1 is out

### ISSUE THREAD

**Issue by eldiener** [niXman/mingw-builds#538]
Gcc 11.1 is out as of 04/27. Can we have support for it here please ?

**Comment by bence42** [comment]
FYI I tried, but python won't build.
Probably doesn't matter but I've used binutils 2.36.1 instead of 2.35.1, gmp 6.2.1 instead of 6.2.0 and mpc 1.2.1 instead of 1.1.0

**Comment by Furniel** [comment]
Working on update, need some time to update all outdated utils and check all builds

**Comment by bence42** [comment]
@Furniel If you plan to update binutils to 2.36.1, it seems that the tk 8.6.10 needs to be patched. It looks like a bug in the handwritten assembly is triggered by the new ld. ( I might be wrong).
See https://github.com/tcltk/tk/pull/6/commits/892a3d64076baacbf011e008eda9a43660da05e5
Plus, it seems tkWin32Dll.c needs another fix from the tk 8.6.11 release. That was the reason for my above python build fail.
