### ISSUE TITLE
issue building with the following options: ./build --mode=gcc-9.3.0 --arch=x86_64 --threads=posix --exceptions=sjlj --enable-languages=c,c++

### ISSUE THREAD

**Issue by hodgeheg99** [niXman/mingw-builds#541]
Hi, I am attempting to build a dual targeted version of the mingw compiler using your scripts.
I followed your readme and used the following command in msys2:

`./build --mode=gcc-9.3.0 --arch=x86_64 --threads=posix --exceptions=sjlj --enable-languages=c,c++`

Here is the output that I get:

`$ ./build --mode=gcc-9.3.0 --arch=x86_64 --threads=posix --exceptions=sjlj --enable-languages=c,c++
-> Checking OS bitness... 64-bit
-> Checking OS type... MINGW32_NT-10.0-18363
-> Checking for installed packages... done
-> i686 toolchain
--> Toolchain installed.
-> x86_64 toolchain
--> Toolchain installed.
-> start building x86_64-9.3.0-multilib-posix-sjlj-rt_v5 with "c,c++" languages supported
-> libiconv-x86_64
---> libiconv-1.16.tar.gz downloaded
---> libiconv-1.16.tar.gz unpacked
---> patched
---> configured
---> built
---> installed
-> libiconv-i686
---> libiconv-1.16.tar.gz downloaded
---> libiconv-1.16.tar.gz unpacked
---> patched
---> configured
---> built
---> installed
-> zlib-x86_64
---> zlib-1.2.11.tar.xz downloaded
---> zlib-1.2.11.tar.xz unpacked
---> patched
--> configure...
error!
`

`/bin/sh: ./configure: No such file or directory`

**Comment by beckerzito** [comment]
I'm having the same problem.

Any update on that?

**Comment by niXman** [comment]
what branch was used?

**Comment by beckerzito** [comment]
Master

**Comment by beckerzito** [comment]
@niXman I realized that it haves using the 'sjlj' exception model

**Comment by niXman** [comment]
try `develop` branch

**Comment by hodgeheg99** [comment]
Thank you very much, I can confirm this also resolved my issue :)
