### ISSUE TITLE
bcrypt link error when building gdb

### ISSUE THREAD

**Issue by kapoisu** [niXman/mingw-builds#543]
I'm trying to build gcc-11.1.0 on Windows 10 with the following command:
```
./build --mode=gcc-11.1.0 --arch=x86_64 --exceptions=seh --threads=posix --enable-languages=c,c++ --cflags='-Wno-format'
```
There seems to be a link error when building gdb:
```
C:/msys64/home/user/mingw-gcc-11.1.0/x86_64-1110-posix-seh-rt_v7/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../gnulib/import/libgnu.a(getrandom.o):getrandom.c:(.text+0x21): undefined reference to `BCryptGenRandom'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:1866: gdb.exe] Error 1
make[2]: Leaving directory '/home/user/mingw-gcc-11.1.0/x86_64-1110-posix-seh-rt_v7/build/gdb-10.2/gdb'
make[1]: *** [Makefile:10412: all-gdb] Error 2
make[1]: Leaving directory '/home/user/mingw-gcc-11.1.0/x86_64-1110-posix-seh-rt_v7/build/gdb-10.2'
make: *** [Makefile:866: all] Error 2
```
I wonder if gunlib configuration causes the problem?
```
configure:20640: checking bcrypt.h presence
configure:20640: x86_64-w64-mingw32-gcc -E  conftest.c
configure:20640: $? = 0
configure:20640: result: yes
configure:20640: WARNING: bcrypt.h: present but cannot be compiled
configure:20640: WARNING: bcrypt.h:     check for missing prerequisite headers?
configure:20640: WARNING: bcrypt.h: see the Autoconf documentation
configure:20640: WARNING: bcrypt.h:     section "Present But Cannot Be Compiled"
configure:20640: WARNING: bcrypt.h: proceeding with the compiler's result
configure:20640: checking for bcrypt.h
configure:20640: result: no
configure:20650: checking whether the bcrypt library is guaranteed to be present
configure:20670: x86_64-w64-mingw32-gcc -c -O2 -pipe -fno-ident -Wno-format -I/home/user/mingw-gcc-11.1.0/x86_64-1110-posix-seh-rt_v7/mingw64/opt/include -I/home/user/mingw-gcc-11.1.0/prerequisites/x86_64-zlib-static/include -I/home/user/mingw-gcc-11.1.0/prerequisites/x86_64-w64-mingw32-static/include -D__USE_MINGW_ANSI_STDIO=1 -fcommon -D__USE_MINGW_ACCESS  conftest.c >&5
configure:20670: $? = 0
configure:20678: result: yes
```

**Comment by jcbrill** [comment]
I ran in to the same problem and may have found a workaround.

There is a gdb patch from October 2020 that appears to address this issue:
> _gnulib: Ensure all libraries are used when building gdb/gdbserver_
> https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=361cb219351d8b7e39e1962fe77f40aa80657b27;ds=sidebyside

However, this patch and later modifications do not appear to be present in the gdb 10 branch or the 10.2 release.

The patch linked to above contains references to the following gdb files:
- gdb/ChangeLog
- gdb/Makefile.in
- gdbserver/ChangeLog
- gdbserver/Makefile.in
- gnulib/ChangeLog
- gnulib/Makefile.gnulib.inc.in
- gnulib/Makefile.in
- gnulib/configure
- gnulib/configure.ac

During testing, I manually removed the diffs for the 3 Changelog files.  The modified patch contains references to the following gdb files:
- gdb/Makefile.in
- gdbserver/Makefile.in
- gnulib/Makefile.gnulib.inc.in
- gnulib/Makefile.in
- gnulib/configure
- gnulib/configure.ac

The 'raw' content linked above was saved as _gdb-10.2-fix-gnulib-dependecies.patch_, the 3 Changelog diffs were manually removed, and a leading comment was added indicating the 3 Changelog diffs were removed.  I am not sure of the protocol for these types of changes to an existing patch.

The modified patch, _gdb-10.2-fix-gnulib-dependecies.patch_, was placed in the the mingw-builds/patches/gdb folder.

The following was added to the gdb.sh script (mingw-builds/scripts/gdb) in the PKG_PATCHES section:
`$( [[ ${PKG_VERSION} == 10.2 ]] && { echo "gdb/gdb-10.2-fix-gnulib-dependecies.patch"; } )`

I'm hoping the above only applies the patch to gdb version 10.2.  Bash scripts are completely foreign to me.

A multilib, bootstrapall build of 8.5, v9, win32, sjlj seems to have successfully linked bcrypt when building gdb/gdbserver where it failed earlier.  Builds for 9.4, 10.3, and 11.1 are pending...

A zip archive containing the modified patch is attached:
[gdb-10.2-fix-gnulib-dependecies.patch.zip](https://github.com/niXman/mingw-builds/files/6671308/gdb-10.2-fix-gnulib-dependecies.patch.zip)

Caveats:
- "config clean" has not been tested. 
- gdb.exe/gdbserver.exe have not been tested.

**Comment by kapoisu** [comment]
> 
> 
> I ran in to the same problem and may have found a workaround.
> 
> There is a gdb patch from October 2020 that appears to address this issue:
> 
> > _gnulib: Ensure all libraries are used when building gdb/gdbserver_
> > https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=361cb219351d8b7e39e1962fe77f40aa80657b27;ds=sidebyside
> 
> However, this patch and later modifications do not appear to be present in the gdb 10 branch or the 10.2 release.
> 
> The patch linked to above contains references to the following gdb files:
> 
>     * gdb/ChangeLog
> 
>     * gdb/Makefile.in
> 
>     * gdbserver/ChangeLog
> 
>     * gdbserver/Makefile.in
> 
>     * gnulib/ChangeLog
> 
>     * gnulib/Makefile.gnulib.inc.in
> 
>     * gnulib/Makefile.in
> 
>     * gnulib/configure
> 
>     * gnulib/configure.ac
> 
> 
> During testing, I manually removed the diffs for the 3 Changelog files. The modified patch contains references to the following gdb files:
> 
>     * gdb/Makefile.in
> 
>     * gdbserver/Makefile.in
> 
>     * gnulib/Makefile.gnulib.inc.in
> 
>     * gnulib/Makefile.in
> 
>     * gnulib/configure
> 
>     * gnulib/configure.ac
> 
> 
> The 'raw' content linked above was saved as _gdb-10.2-fix-gnulib-dependecies.patch_, the 3 Changelog diffs were manually removed, and a leading comment was added indicating the 3 Changelog diffs were removed. I am not sure of the protocol for these types of changes to an existing patch.
> 
> The modified patch, _gdb-10.2-fix-gnulib-dependecies.patch_, was placed in the the mingw-builds/patches/gdb folder.
> 
> The following was added to the gdb.sh script (mingw-builds/scripts/gdb) in the PKG_PATCHES section:
> `$( [[ ${PKG_VERSION} == 10.2 ]] && { echo "gdb/gdb-10.2-fix-gnulib-dependecies.patch"; } )`
> 
> I'm hoping the above only applies the patch to gdb version 10.2. Bash scripts are completely foreign to me.
> 
> A multilib, bootstrapall build of 8.5, v9, win32, sjlj seems to have successfully linked bcrypt when building gdb/gdbserver where it failed earlier. Builds for 9.4, 10.3, and 11.1 are pending...
> 
> A zip archive containing the modified patch is attached:
> [gdb-10.2-fix-gnulib-dependecies.patch.zip](https://github.com/niXman/mingw-builds/files/6671308/gdb-10.2-fix-gnulib-dependecies.patch.zip)
> 
> Caveats:
> 
>     * "config clean" has not been tested.
> 
>     * gdb.exe/gdbserver.exe have not been tested.

Thanks a lot! I've tried this solution and built successfully for gcc-11.1.0.

**Comment by jcbrill** [comment]
You're welcome.  Until your response was posted, I didn't realize there was a spelling error for *dependencies* in the patch name and in the *gdb.sh* addition.

The corrected patch filename is attached for future reference:
[gdb-10.2-fix-gnulib-dependencies.patch.zip](https://github.com/niXman/mingw-builds/files/6680602/gdb-10.2-fix-gnulib-dependencies.patch.zip)

The following was added/corrected in the gdb.sh script (mingw-builds/scripts/gdb) in the PKG_PATCHES section:
`$( [[ ${PKG_VERSION} == 10.2 ]] && { echo "gdb/gdb-10.2-fix-gnulib-dependencies.patch"; } )`

The following local builds were successful subject to the caveats below:
```
./build --mode=gcc-8.5.0 --arch=i686 --threads=win32 --exceptions=sjlj --enable-languages=c,c++ --rt-version=v9 --jobs=4 --rev=0 --bootstrapall
./build --mode=gcc-8.5.0 --arch=x86_64 --threads=win32 --exceptions=sjlj --enable-languages=c,c++ --rt-version=v9 --jobs=4 --rev=0 --bootstrapall

./build --mode=gcc-9.4.0 --arch=i686 --threads=win32 --exceptions=sjlj --enable-languages=c,c++ --rt-version=v9 --jobs=4 --rev=0 --bootstrapall
./build --mode=gcc-9.4.0 --arch=x86_64 --threads=win32 --exceptions=sjlj --enable-languages=c,c++ --rt-version=v9 --jobs=4 --rev=0 --bootstrapall

./build --mode=gcc-10.3.0 --arch=i686 --threads=win32 --exceptions=sjlj --enable-languages=c,c++ --rt-version=v9 --jobs=4 --rev=0 --bootstrapall
./build --mode=gcc-10.3.0 --arch=x86_64 --threads=win32 --exceptions=sjlj --enable-languages=c,c++ --rt-version=v9 --jobs=4 --rev=0 --bootstrapall

./build --mode=gcc-11.1.0 --arch=i686 --threads=win32 --exceptions=sjlj --enable-languages=c,c++ --rt-version=v9 --jobs=4 --rev=0 --bootstrapall
./build --mode=gcc-11.1.0 --arch=x86_64 --threads=win32 --exceptions=sjlj --enable-languages=c,c++ --rt-version=v9 --jobs=4 --rev=0 --bootstrapall
```
Notes:
* Support for mingw-w64 runtime version v9 was added to the develop branch yesterday.

Caveats:
* Patch `gcc/0020-libgomp-Don-t-hard-code-MS-printf-attributes.patch` was added to scripts `gcc-8.5.0.sh` and `gcc-9.4.0.sh`.
* The lto-tests were manually removed based on a local legacy patch and therefore not invoked.
* None of the generated binaries have been tested yet other than tests performed at the end of the build.
* gdb config clean has not been tested.
* gdb.exe and gdbserver.exe have not been tested.
* The build logs have not been reviewed for warnings or errors.

Currently, all (relatively minor) changes are in my repository:
https://github.com/jcbrill/mingw-builds/tree/jbrill-develop

If the remaining tests are successful, I can issue a PR.

**Comment by niXman** [comment]
any news about the PR?

**Comment by jcbrill** [comment]
Preparing it now.  Will issue shortly...

**Comment by niXman** [comment]
closed as solved.

thank you @jcbrill !
