### ISSUE TITLE
build support installation behind proxy

### ISSUE THREAD

**Issue by labba** [niXman/mingw-builds#546]
hi,

i have tried to install this build behind a proxy and gotten some interesting results that you might want to change in order to support the build behind a proxy. usually just adding to msys export for http/https proxy is enought but in the case of the build it's not.

1.  in many stages of the build, there is a use of:  "wget"  - this break the proxy - i solved this by manually going to "C:\msys64\etc\wgetrc" file and adding use_proxy=yes and adding the relevent proxy we have.

would be nice if the wget will take the existing system configuration to it's command line "-e use_proxy=yes" and the needed proxy list.

2. "git://" - the use of git protocol over "https://" will cause breaking proxy as well - i have just "search" and "replace" all places so my build won't break.

i think when a proxy setting is detected it would be better to use the https and not the git protocol.

Thank you for your amazing work here!

**Comment by niXman** [comment]
great!

patched are welcome ;)

**Comment by starg2** [comment]
> 2\. "git://" - the use of git protocol over "https://" will cause breaking proxy as well - i have just "search" and "replace" all places so my build won't break.

I think that was fixed by #612.

**Comment by niXman** [comment]
@labba could you please close the issue if is solved?
