### ISSUE TITLE
"expat.sh" pointing to a non-existing expat-2.2.9.tar.xz file

### ISSUE THREAD

**Issue by labba** [niXman/mingw-builds#547]
when tried to compile gcc 8.3.0 i have gotten to an error and from some reason , the file "expat-2.2.9.tar.xz" doesn't exist anymore (i think there is only "lz" file) in the referenced address in the script:  https://sourceforge.net/projects/expat/files/expat/2.2.9/

i have found that the "xz" file does exist in the github: https://github.com/libexpat/libexpat/releases/tag/R_2_2_9

so this beak current compilation ..

**Comment by niXman** [comment]
where did you find that version?
as far as I can see, the current expat version in use is 2.4.1: https://github.com/niXman/mingw-builds/blob/develop/scripts/expat.sh#L38

**Comment by labba** [comment]
in the master of  https://github.com/niXman/mingw-builds/blob/master/scripts/expat.sh the version it try to download is 2.2.9 i took the master .. didn't know that i should take the develop one ..

**Comment by niXman** [comment]
yes, the `master` branch contains releases only.

please close.

**Comment by labba** [comment]
i have tried to build 8.3.0 from Develop branch and it fails.

build command:
./build --mode=gcc-8.3.0 --arch=i686 --threads=win32 --enable-languages=c,c++ --no-multilib

attached logs in zip file.
[log.zip](https://github.com/niXman/mingw-builds/files/6855596/log.zip)

many errors of "error: redefinition"

**Comment by niXman** [comment]
please put the error messages here, dont hide it in the archive.

**Comment by labba** [comment]
sure:
in the log found the following errors:

1)  ../../src/mingw-w64/mingw-w64-crt/libsrc/ws2tcpip/in6_addr_equal.c:9:5: error: redefinition of 'IN6_ADDR_EQUAL'

2) ../../src/mingw-w64/mingw-w64-crt/libsrc/ws2tcpip/in6addr_isloopback.c:19:5: error: redefinition of 'IN6ADDR_ISLOOPBACK'

3) ../../src/mingw-w64/mingw-w64-crt/libsrc/ws2tcpip/in6addr_isany.c:19:5: error: redefinition of 'IN6ADDR_ISANY'

**Comment by labba** [comment]
no news on this ?

**Comment by niXman** [comment]
no, because the issue named as `"expat.sh" pointing to a non-existing expat-2.2.9.tar.xz` but the errors is about `mingw-w64-crt` project.

also over the past month in several tickets other users were able to successfully build mingw-w64, although initially they had problems with another.

**Comment by labba** [comment]
ok i will try to re-build it again and report if i have any news or lack of them (meaning no issue was found)

thanks!
