### ISSUE TITLE
Can't pass test when building i686

### ISSUE THREAD

**Issue by DynamicLoader** [niXman/mingw-builds#558]
HI,

I am trying to build MinGW-w64 i686 toolchain.With gcc11.2.0,both x86_64 and i686 is built normally,but i686 toolchain tests alway failed.The failed test is dll_test2,which is complied normally but executed failed with return code 3.Built with gcc11.1.0 is the same(test failed).
Built with posix.rt-v9.0.0

Any suggestion?

**Comment by Prince213** [comment]
Could you please paste your commandline here?

**Comment by DynamicLoader** [comment]
Sure.I build this on Github actions,link [here](https://github.com/Lucy2003/MinGW-w64-ActionBuild/runs/3326511773?check_suite_focus=true)

Command line:`./build --mode=gcc-11.1.0 --arch=i686 --exceptions=dwarfseh --threads=posix --rt-version=v9.0.0 --enable-languages=c,c++ --jobs=2 --bin-compress --cflags="-Wno-format"`

**Comment by DynamicLoader** [comment]
Any progress?

**Comment by revelator** [comment]
sounds a bit like the problems we have on msys2 mingw32 with dwarf exceptions being broken in gcc-11. some headway has been made but need atleast binutils-2.37 because the older binutils do not support the new dwarf5 format correctly. Also building 32 bit ada is broken :/

**Comment by niXman** [comment]
@revelator what should we do? any patches?

**Comment by revelator** [comment]
atm still investigating, so far no luck unfortunatly :(. It has been reported upstream though it seems the gcc devs are also a bit baffled by this.

**Comment by revelator** [comment]
strangely using an sjlj exception based gcc as bootstrap compiler allows the dwarf version to build.
ada will also work when done this way, but bootstrapping a build with this compiler will fail same as using any other dwarf exception based compiler for bootstrapping.

**Comment by revelator** [comment]
well dwarf ada does in fact build when bootstrapped with the sjlj compiler but it does not work, compiling gprbuild segfaults the gnat compiler, the sjlj version does work though.

**Comment by cristianadam** [comment]
GitHub Actions build is green at https://github.com/niXman/mingw-builds/actions/runs/1415861367 including i686.

The failure was due to ... `grep` version 3.6 that msys2 used to have. Latest msys2 grep package was downgraded to version `3.0` which works fine, as seen in the GitHub Actions build.

See https://github.com/msys2/MINGW-packages/issues/9771 for more details.

**Comment by DynamicLoader** [comment]
Glad to know it.I will try it.

**Comment by revelator** [comment]
aye was grep causing problems, luckily someone was awake and caught it :)

**Comment by DynamicLoader** [comment]
Thank everyone.The issue has benn solved.
