### ISSUE TITLE
Code Profiler file "empty".

### ISSUE THREAD

**Issue by NickCNA** [niXman/mingw-builds#560]
I compiled a few GCC versions using MSYS2 / mingw-builds (develop branch) using the following command lines:

./build --mode=gcc-11.2.0 --arch=x86_64 --enable-languages=c,c++,fortran --buildroot=/f/Compiled/mingw64 --rt-version=v8 --exceptions=seh --jobs=24 --rev=0 --threads=win32 --bin-compress

./build --mode=gcc-11.2.0 --arch=x86_64 --enable-languages=c,c++,fortran --buildroot=/f/Compiled/mingw64 --rt-version=v9 --exceptions=seh --jobs=24 --rev=0 --threads=win32 --bin-compress

./build --mode=gcc-10.3.0 --arch=x86_64 --enable-languages=c,c++,fortran --buildroot=/f/Compiled/mingw64 --rt-version=v8 --exceptions=seh --jobs=24 --rev=0 --threads=win32 --bin-compress

I'm using Code::Blocks as my IDE. When I enable the code profiling compiler option and then use the code profiler plugin there window is "blank" with no contents.

When I downloaded someone else's mingw build of GCC 10.3.0 and used that the code profiler worked as expected.

**Comment by niXman** [comment]
> When I downloaded someone else's mingw build of GCC 10.3.0

which one?

and provide me the info how can I reproduce the issue using that mingw

**Comment by NickCNA** [comment]
It was this one that worked: https://github.com/MNRK01/myGCCBuilds/releases/download/10.3.0/x86_64-10.3.0-release-win32-seh-rt_v8-rev0.7z

The -pg compilation flag is used then, after the program was run, in Code::Blocks, Plugins > Code Profiler.

**Comment by NickCNA** [comment]
Solved: adding "-no-pie" to compiler and linker settings allows gprof to parse the gmon.out file correctly.

**Comment by niXman** [comment]
great!

please close this issue.

**Comment by NickCNA** [comment]
Closed accordingly.
