### ISSUE TITLE
Automatically apply patch to fix libgomp compilation errors

### ISSUE THREAD

**Issue by MarkKoz** [niXman/mingw-builds#562]
[This](https://sourceforge.net/p/mingw-w64/bugs/853/) issue was reported and a patch was provided [here](https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/21abc969-03b2-4f89-de64-c58b3434f736%40gmail.com/#msg37201019). I had to use it to build GCC 6.5.0 successfully. It'd be nice if the build scripts for GCC could automatically apply this patch when it's needed. Of course the line numbers would be different depending on the GCC version.

**Comment by niXman** [comment]
but we have that patch too: https://github.com/niXman/mingw-builds/blob/develop/patches/gcc/0020-libgomp-Don-t-hard-code-MS-printf-attributes.patch

just add it to the gcc-6.5.0.sh script and do a PR.

**Comment by MarkKoz** [comment]
Thanks. I didn't realise there were mechanisms already in place for doing this.
