### ISSUE TITLE
No rule to make target build-x86_64-w64-mingw32/libiberty/pic/libiberty.a

### ISSUE THREAD

**Issue by MarkKoz** [niXman/mingw-builds#563]
I'm using the latest ref in the `develop` branch (7187b70e953fa6c1d9fef47005c7385d80c64ddf at the time of writing) and running

```sh
./build --mode=gcc-6.5.0 --arch=x86_64 --exceptions=seh --threads=posix --buildroot=../gcc-6.5.0
```

It fails when building `gcc-6.5.0`:

```
make[3]: Entering directory '/c/Users/Mark/scoop/persist/msys2/home/Mark/gcc-6.5.0/x86_64-650-posix-seh-rt_v9/build/gcc-6.5.0/gcc'
TARGET_CPU_DEFAULT="" \
HEADERS="auto-host.h ansidecl.h config/i386/xm-mingw32.h" DEFINES="" \
/bin/sh ../../../../src/gcc-6.5.0/gcc/mkconfig.sh config.h
TARGET_CPU_DEFAULT="" \
HEADERS="options.h insn-constants.h config/vxworks-dummy.h config/i386/biarch64.h config/i386/i386.h config/i386/unix.h config/i386/bsd.h config/i386/gas.h config/dbxcoff.h config/i386/cygming.h config/i386/mingw-pthread.h config/i386/mingw32.h config/i386/mingw-w64.h config/i386/mingw-stdint.h config/initfini-array.h defaults.h" DEFINES="LIBC_GLIBC=1 LIBC_UCLIBC=2 LIBC_BIONIC=3 LIBC_MUSL=4" \
/bin/sh ../../../../src/gcc-6.5.0/gcc/mkconfig.sh tm.h
TARGET_CPU_DEFAULT="" \
HEADERS="config/i386/i386-protos.h tm-preds.h" DEFINES="" \
/bin/sh ../../../../src/gcc-6.5.0/gcc/mkconfig.sh tm_p.h
TARGET_CPU_DEFAULT="" \
HEADERS="auto-host.h ansidecl.h config/i386/xm-mingw32.h" DEFINES="" \
/bin/sh ../../../../src/gcc-6.5.0/gcc/mkconfig.sh bconfig.h
make[3]: *** No rule to make target '../build-x86_64-w64-mingw32/libiberty/pic/libiberty.a', needed by 'build/genmddeps.exe'.  Stop.
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/c/Users/Mark/scoop/persist/msys2/home/Mark/gcc-6.5.0/x86_64-650-posix-seh-rt_v9/build/gcc-6.5.0/gcc'
make[2]: *** [Makefile:4394: all-stage1-gcc] Error 2
make[2]: Leaving directory '/c/Users/Mark/scoop/persist/msys2/home/Mark/gcc-6.5.0/x86_64-650-posix-seh-rt_v9/build/gcc-6.5.0'
make[1]: *** [Makefile:19440: stage1-bubble] Error 2
make[1]: Leaving directory '/c/Users/Mark/scoop/persist/msys2/home/Mark/gcc-6.5.0/x86_64-650-posix-seh-rt_v9/build/gcc-6.5.0'
make: *** [Makefile:917: all] Error 2

```

I'm not sure if this is a configuration issue on my end, something wrong with the build scripts, or an upstream GCC issue. I came across three other people experiencing the same error ([1](https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/CAMxMwyLJss7%2BfwUbFZMJ%3DrerJqhtAU00TKjP_74YkSQTimLs-A%40mail.gmail.com/#msg34333094), [2](https://gcc.gnu.org/bugzilla//show_bug.cgi?format=multiple&id=67275), [3](https://www.spinics.net/lists/gcchelp/msg50096.html)). Is there a way to fix this on your end?

As hinted by the GCC bug report, the workaround is to use `--static-gcc` i.e. avoid `--enabled-host-shared`. However, `--enabled-host-shared` is used by default here, so it's more likely to encounter this error. And, of course, it'd be nice to actually be able to compile with this option.

**Comment by niXman** [comment]
> or an upstream GCC issue

looks like yes because I have never seen this error before on 8/9/10 versions

**Comment by MarkKoz** [comment]
Unfortunately the bug reported in GCC's tracker hasn't had any response. Feel free to close this if you think there's nothing that can be done in the build scripts to fix this.

**Comment by jbo-85** [comment]
This was fixed upstream in GCC 11.x: https://gcc.gnu.org/bugzilla//show_bug.cgi?format=multiple&id=67275
patch: https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=c83027f32d9cca84959c7d6a1e519a0129731501
It's still broken in GCC 10 and probably all prior versions. I think it started when the build-script was changed to use --enable-host-shared in https://github.com/niXman/mingw-builds/commit/4b15c31ae5a7f844d09c2170b2549d4a015f280d. 

Command:
./build --mode=gcc-10-branch --arch=x86_64 --exceptions=dwarfseh --rt-version=v9 --threads=posix --enable-languages=c,c++ --no-multilib --with-testsuite --no-bootstrap --cflags='-Wno-error' --cxxflags='-Wno-error'
