### ISSUE TITLE
tag a new release

### ISSUE THREAD

**Issue by ericLemanissier** [niXman/mingw-builds#575]
Hi, It's awesome that this project gets built successfully by github actions !
Would it be possible to make a tag version ? [The last one](https://github.com/niXman/mingw-builds/releases/tag/v-5.0.0) is quite outdated now, and that would make binaries available at a stable URL (like https://github.com/cristianadam/mingw-builds/releases).
This would enable this new version to be packaged in conan, as pre-built binaries.
I tried to make a build recipe for conan, unfortunately it cannot work, because conan's MSYS2 has gcc pre-installed, so the build fails expectedly with `remove from PATH any gcc.exe or MingW gcc.exe.`

**Comment by niXman** [comment]
unfortunately I'm not familiar with github actions...

@cristianadam can you help with this please?

**Comment by ericLemanissier** [comment]
AFAIU, you just have to create a git tag starting with `v`, and github will do the right thing. @cristianadam already set-up a github actions which creates the release package and publishes it on github as part of https://github.com/niXman/mingw-builds/commit/c680028de456812c10c25ecef78107c06ea1550c

**Comment by cristianadam** [comment]
The GitHub Actions yml file is doing the release, for https://github.com/cristianadam/mingw-builds/releases/tag/v11.2.0-rev1 I've done:

```
git tag -a v11.2.0-rev1 -m "Release v11.2.0-rev1"
git push origin v11.2.0-rev1
```
GitHub Actions will build the tagged commit, create a release, and upload the binaries.

Afterwards I edited the release page with the contents.

**Comment by ericLemanissier** [comment]
FYI, I just did what @cristianadam described in the last message on my fork, tagging the last commit on develop as v9, and it nicely created https://github.com/ericLemanissier/mingw-builds/releases automagically , which are then easily packaged by conan.

**Comment by cristianadam** [comment]
Please note that previously https://sourceforge.net/projects/mingw-w64/files/ got the version number from the GCC version. I also used the GCC version to tag my fork's [v11.2.0](https://github.com/cristianadam/mingw-builds/releases/tag/v11.2.0-rev1) release.

The previous tags https://github.com/niXman/mingw-builds/tags were independent from GCC or runtime versions. It doesn't look easy to pick a tag version.

**Comment by ericLemanissier** [comment]
Happy new year every one ! @niXman how far do you think we are from tagging a new version ?

**Comment by niXman** [comment]
@ericLemanissier @cristianadam 

guys, perhaps it makes sense to create a separate github project (for example `mingw-builds-binary`, I can do it right now) and make the necessary changes to the github-actions script so that when creating a new GCC version tag, it downloads the latest version of the scripts and builds Mingw?

**Comment by ericLemanissier** [comment]
That's a possibility, so the only source files in this repo would be the github action right?

**Comment by niXman** [comment]
I think yes.

but we need to change the github-actions script so it downloads mingw-builds scripts too.

any suggestions how to name that project? I will create it.

**Comment by niXman** [comment]
- mingw-builds-binary ?
- mingw-executables ?
- mingw-windows ?

**Comment by ericLemanissier** [comment]
mingw-builds-binary sounds clearer to me. Or maybe mingw-builds-binaries? Or mingw-builds-builds ;)

**Comment by niXman** [comment]
> Or maybe mingw-builds-binaries?

great, will do now!

**Comment by niXman** [comment]
done: https://github.com/niXman/mingw-builds-binaries

**Comment by ericLemanissier** [comment]
https://github.com/niXman/mingw-builds-binaries/releases/tag/11.2.0-rt_v9-rev0
Thanks !
