### ISSUE TITLE
expat-2.4.1 - disappears

### ISSUE THREAD

**Issue by kov-serg** [niXman/mingw-builds#582]
--> download expat-2.4.1.tar.xz...
error 8

https://sourceforge.net/projects/expat/files/expat/2.4.1/

expat-2.4.1-RENAMED-VULNERABLE-PLEASE-USE-2.4.7-INSTEAD

changing scripts/expat.sh to PKG_VERSION=2.4.7 cause:
Not found level for patch expat/expat_mingw_tests_fix.patch, error=1

**Comment by cristianadam** [comment]
This is what the pull request at https://github.com/niXman/mingw-builds/pull/579 fixes.

**Comment by niXman** [comment]
#581 was merged so this issue will closed.
