### ISSUE TITLE
Patch Errors Compiling 12.1.0

### ISSUE THREAD

**Issue by NickCNA** [niXman/mingw-builds#589]
I tried to compile 12.1.0 and got patching errors with:

	gcc/gcc-libgomp-ftime64.patch
	gcc/0020-libgomp-Don-t-hard-code-MS-printf-attributes.patch
	gcc/gcc-10-libgcc-ldflags.patch

Commenting out these patches in 12.1.0.sh gave a compile error.

**Comment by guyutongxue** [comment]
I've already tried a successful build of GCC 12.1.0. I had run into some patch errors, but I've fixed them in the PR.

My build arg is (likely):
```
--mode=gcc-12.1.0 --arch=x86_64 --exceptions=seh --threads=posix --rt-version=v10 --enable-languages=c,c++
```

So I don't know why you're experiencing these errors...

**Comment by NickCNA** [comment]
I've purged the build directory and have started again with:

./build --mode=gcc-12.1.0 --arch=x86_64 --enable-languages=c,c++,fortran --buildroot=/h/Compiled/mingw64 --rt-version=v10 --exceptions=seh --jobs=24 --rev=0 --threads=win32 --bin-compress

**Comment by NickCNA** [comment]
Failed again so I removed MSYS as well, reinstalled, reinstalled mingw-builds and was successful with the above command line.
