### ISSUE TITLE
Reference to git.code.sf.net is broken in building process 

### ISSUE THREAD

**Issue by augustosisa** [niXman/mingw-builds#602]
I had tried to build MinGW-gcc-4.x in Msys2 but during the process, I get an error related to connection issues, even though most of the packages before that call worked perfectly. I look for a file with that reference, but I didn't find it.

```
./build --mode=gcc-4.9.2 --arch=x86_64

...

Cloning into '/home/<user>/mingw-gcc-4.9.2/src/mingw-w64'...
fatal: unable to connect to git.code.sf.net:
git.code.sf.net[0: 216.105.38.16]: errno=Connection timed out
```

**Comment by rallenh** [comment]
@augustosisa ,

Can you provide the complete command? mingw-builds won't get git sources unless it's told to do so. The "normal" mode of using it, it downloads released tarballs from various places on the Internet.

In addition, for a GCC that old you are probably going to need to be specific about which mingw-w64 runtime you want. This could also be where mingw-builds is attempting a clone of a repo. Check the --rt_version build option here https://github.com/niXman/mingw-builds/blob/develop/build#L71.

Did you check https://sourceforge.net/projects/mingw-w64/files/ ?
