### ISSUE TITLE
to test the my first build of windows hosted mingw-w64 using linux cross compiler

### ISSUE THREAD

**Issue by niXman** [niXman/mingw-builds#615]
hi!

@here

just now I have successfully build the my first build of windows hosted mingw-w64 targeting `x86_64, posix, seh, non-multilib` compiler using linux cross compiler!

it would be awesome if anyone can try to test it for use on windows for some of projects =)

Virus Total report: https://www.virustotal.com/gui/file/721b1209b9eca4391dc86aa56004a1a9136dec813a1ec1bac083395cfa200afc?nocache=1

sha256: 721b1209b9eca4391dc86aa56004a1a9136dec813a1ec1bac083395cfa200afc

https://file.io/8DnNQNZ49DJF (the file will be removed on sep 25)

best!

**Comment by ghost** [comment]
@niXman Could you modify your scripts to be able to cross compile from Linux or any Unix-like environment?

**Comment by niXman** [comment]
yes, that is my plan!

but I have no free time atm... :(
