### ISSUE TITLE
--buildroot does not recognize ~ as msys home directory

### ISSUE THREAD

**Issue by JohannesKauffmann** [niXman/mingw-builds#618]
Running `./build ... --buildroot=~/builddir` results in a `'~'` folder inside of the git clone, which has the `builddir` folder inside it.

Just something I noticed while running the script. Maybe I should've specified the absolute path, I don't know.

**Comment by niXman** [comment]
hmm... will look at this later.

just specify the full path for now.

**Comment by JohannesKauffmann** [comment]
I forgot to mention - this also makes the build fail, as the `builddir` is then also created inside the clone. While the `~/builddir` folder is created, it is completely empty.

But yes, it can be worked around with the full path.

**Comment by niXman** [comment]
@here guys, could someone look at this issue pleased?
I'm so busy... :(
I think it can be solved by additional check for the first char, and when it is `~` - to use `$HOME` and to concat the rest of the string.
or be better to use `eval` after cutting `--buildroot=` prefix string between the lines 228 and 229 here: https://github.com/niXman/mingw-builds/blob/develop/build#L228
