### ISSUE TITLE
No gdb tui?

### ISSUE THREAD

**Issue by quadro9** [niXman/mingw-builds#632]
https://github.com/niXman/mingw-builds-binaries/issues/33
is it possible to enable tui?

**Comment by niXman** [comment]
@here guys, does anyone remember why we build gdb without TUI support?

**Comment by niXman** [comment]
@quadro9 you cat try it yourself.
just change [this](https://github.com/niXman/mingw-builds/blob/develop/scripts/gdb.sh#L80) line to `--enable-tui` and start to build a toolchain.

can you?

**Comment by quadro9** [comment]
well, i'd like to have a ready build with tui, without build it myself ) as I know msys made builds with tui, so it is strange that here it is disabled

**Comment by niXman** [comment]
done: https://github.com/niXman/mingw-builds/commit/a8243588e5b54a8a69707bb53e79e5f6462b1eec

bootstrapped locally - OK.
will be avail in the next releases.
