### ISSUE TITLE
any way to chnage 'msvcrt' to 'ucrt' using script?

### ISSUE THREAD

**Issue by coder-debankur** [niXman/mingw-builds#646]

**Comment by starg2** [comment]
What do you mean by "change 'msvcrt' to 'ucrt'"?

**Comment by coder-debankur** [comment]
nvm, i figured it out, but now another problem rise. Error while making mingw build in MSYS2 at "building gcc-13.1.0"
 i used command,

./build --mode=gcc-13.1.0 --arch=x86_64 --with-default-msvcrt=ucrt --rt-version=v11 --threads=win32 --exceptions=seh  --bin-compress --enable-languages=c,c++

this gives error when building gcc-13.1.0

**Comment by starg2** [comment]
Please share the log file.
