### ISSUE TITLE
Not found level for patch

### ISSUE THREAD

**Issue by lunatichai** [niXman/mingw-builds#664]
Not found level for patch mingw-w64/9002-crt-Provide-wrappers-for-exit-in-libmingwex.patch, error=1
для $ ./build --mode=gcc-13.2.0 --arch=x86_64 --threads=win32
ветка develop
также пробовал gcc 8.3.0 и gcc 9.3.0

**Comment by niXman** [comment]
very strange... because on Oct 2 I was able to successfully build 13.2.0: https://github.com/niXman/mingw-builds-binaries/releases/tag/13.2.0-rt_v11-rev0
