### ISSUE TITLE
mingw-w64-crt: automake execution failed

### ISSUE THREAD

**Issue by zxunge** [niXman/mingw-builds#678]
![Screenshot_2024_0619_095813](https://github.com/niXman/mingw-builds/assets/121007356/eba23970-64f0-4c37-b005-c44ba2a5e9c3)
[logs_25059854736.zip](https://github.com/user-attachments/files/15894443/logs_25059854736.zip)
Hi niXman,
       Your scripts are great! But when I tried using your scripts in GitHub Actions, I met an error. Please see [my repo](https://github.com/zxunge/MinGW-w64-GCC) and the attached full build log.

**Comment by niXman** [comment]
I think you need to change the used branch to `develop` =)
