### ISSUE TITLE
无法编译10.1.0

### ISSUE THREAD

**Issue by jianghuyongren** [niXman/mingw-builds#679]
报错
-> mingw-w64-api
--> Doesn't need to download
--> Unpack doesn't need
---> configured
---> built
---> installed
-> mingw-w64-crt
--> Doesn't need to download
--> Unpack doesn't need
--> patching...
Not found level for patch mingw-w64/9001-crt-Mark-atexit-as-DATA-because-it-s-always-overridd.patch, error=1
另外，在编译4.x.x版本时报错无法下载，cloog-0.18.4.tar.gz，访问地址，应该是网站安全证书过期，无法下载

**Comment by niXman** [comment]
please retranslate this to English.
