### ISSUE TITLE
Signing DLLs in sys-root/mingw/bin with SignPath?

### ISSUE THREAD

**Issue by mlocati** [niXman/mingw-builds#684]
I'm publishing the gettext and iconv binaries for Windows ([see here](https://github.com/mlocati/gettext-iconv-windows)).

For the [next release](https://github.com/mlocati/gettext-iconv-windows/pull/18), I'm planning to sign the executables with [SignPath](https://about.signpath.io/product/open-source).

As per [their rules](https://signpath.org/terms), I can only sign the binaries that I compile directly.

The problem is that, for the "shared builds" (that is, executables that rely on DLLs), I also distribute some of the DLLs available in Cygwin MinGW-w64's `sys-root/mingw/bin` directory.

What if MinGW-w64 signed those DLLs too?

**Comment by niXman** [comment]
why can't you build your DLLs using static build of MinGW-W64?

**Comment by mlocati** [comment]
I also offer static builds, but some people prefer shared ones - see https://mlocati.github.io/articles/gettext-iconv-windows.html
