### ISSUE TITLE
Patching error

### ISSUE THREAD

**Issue by faelon777** [niXman/mingw-builds#685]
I use last msys2 for windows msys2.org

SkyNet@m77 MSYS ~/mingw-builds
$ ./build --mode=gcc-11.5.0 --arch=x86_64
....
-> mingw-w64-crt
--> Doesn't need to download
--> Unpack doesn't need
--> patching...
Not found level for patch mingw-w64/9001-v13-crt-Mark-atexit-as-DATA-because-it-s-always-overridd.patch, error=1

and same for rt-11

-> mingw-w64-crt
--> Doesn't need to download
--> Unpack doesn't need
--> patching...
Not found level for patch mingw-w64/9001-v11-crt-Mark-atexit-as-DATA-because-it-s-always-overridd.patch, error=1

**Comment by niXman** [comment]
@starg2 maybe you have some ideas? :)

**Comment by starg2** [comment]
I'll investigate it.
