### ISSUE TITLE
Question Only: What C Runtime Library is Used?

### ISSUE THREAD

**Issue by ghost** [niXman/mingw-builds#686]
Hi, is asking a question acceptable here? Does this toolchain use msvcrt or ucrt? I'm seeking a clang or gcc toolchain for windows that uses ucrt. Thanks kindly.

**Comment by starg2** [comment]
Both msvcrt and ucrt are supported.

By default, it builds toolchains that use msvcrt. Pass the `--with-default-msvcrt=ucrt` option to target ucrt.

**Comment by ghost** [comment]
OK thanks much! I got here from my CLion IDE BTW. The crt difference is probably not a major concern anyway. Have wonderful day!
